// Code generated by mockery v2.52.3. DO NOT EDIT.

package columns

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockColumnService is an autogenerated mock type for the ColumnService type
type MockColumnService struct {
	mock.Mock
}

type MockColumnService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockColumnService) EXPECT() *MockColumnService_Expecter {
	return &MockColumnService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, body
func (_m *MockColumnService) Create(ctx context.Context, body ColumnRequest) (*Column, error) {
	ret := _m.Called(ctx, body)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *Column
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ColumnRequest) (*Column, error)); ok {
		return rf(ctx, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ColumnRequest) *Column); ok {
		r0 = rf(ctx, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Column)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ColumnRequest) error); ok {
		r1 = rf(ctx, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockColumnService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockColumnService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - body ColumnRequest
func (_e *MockColumnService_Expecter) Create(ctx interface{}, body interface{}) *MockColumnService_Create_Call {
	return &MockColumnService_Create_Call{Call: _e.mock.On("Create", ctx, body)}
}

func (_c *MockColumnService_Create_Call) Run(run func(ctx context.Context, body ColumnRequest)) *MockColumnService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ColumnRequest))
	})
	return _c
}

func (_c *MockColumnService_Create_Call) Return(_a0 *Column, _a1 error) *MockColumnService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockColumnService_Create_Call) RunAndReturn(run func(context.Context, ColumnRequest) (*Column, error)) *MockColumnService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, board, column, user
func (_m *MockColumnService) Delete(ctx context.Context, board uuid.UUID, column uuid.UUID, user uuid.UUID) error {
	ret := _m.Called(ctx, board, column, user)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, board, column, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockColumnService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockColumnService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - board uuid.UUID
//   - column uuid.UUID
//   - user uuid.UUID
func (_e *MockColumnService_Expecter) Delete(ctx interface{}, board interface{}, column interface{}, user interface{}) *MockColumnService_Delete_Call {
	return &MockColumnService_Delete_Call{Call: _e.mock.On("Delete", ctx, board, column, user)}
}

func (_c *MockColumnService_Delete_Call) Run(run func(ctx context.Context, board uuid.UUID, column uuid.UUID, user uuid.UUID)) *MockColumnService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockColumnService_Delete_Call) Return(_a0 error) *MockColumnService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockColumnService_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *MockColumnService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, boardID, columnID
func (_m *MockColumnService) Get(ctx context.Context, boardID uuid.UUID, columnID uuid.UUID) (*Column, error) {
	ret := _m.Called(ctx, boardID, columnID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *Column
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*Column, error)); ok {
		return rf(ctx, boardID, columnID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *Column); ok {
		r0 = rf(ctx, boardID, columnID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Column)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, boardID, columnID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockColumnService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockColumnService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - boardID uuid.UUID
//   - columnID uuid.UUID
func (_e *MockColumnService_Expecter) Get(ctx interface{}, boardID interface{}, columnID interface{}) *MockColumnService_Get_Call {
	return &MockColumnService_Get_Call{Call: _e.mock.On("Get", ctx, boardID, columnID)}
}

func (_c *MockColumnService_Get_Call) Run(run func(ctx context.Context, boardID uuid.UUID, columnID uuid.UUID)) *MockColumnService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockColumnService_Get_Call) Return(_a0 *Column, _a1 error) *MockColumnService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockColumnService_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*Column, error)) *MockColumnService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx, boardID
func (_m *MockColumnService) GetAll(ctx context.Context, boardID uuid.UUID) ([]*Column, error) {
	ret := _m.Called(ctx, boardID)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*Column
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*Column, error)); ok {
		return rf(ctx, boardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*Column); ok {
		r0 = rf(ctx, boardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Column)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, boardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockColumnService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockColumnService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - boardID uuid.UUID
func (_e *MockColumnService_Expecter) GetAll(ctx interface{}, boardID interface{}) *MockColumnService_GetAll_Call {
	return &MockColumnService_GetAll_Call{Call: _e.mock.On("GetAll", ctx, boardID)}
}

func (_c *MockColumnService_GetAll_Call) Run(run func(ctx context.Context, boardID uuid.UUID)) *MockColumnService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockColumnService_GetAll_Call) Return(_a0 []*Column, _a1 error) *MockColumnService_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockColumnService_GetAll_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*Column, error)) *MockColumnService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, body
func (_m *MockColumnService) Update(ctx context.Context, body ColumnUpdateRequest) (*Column, error) {
	ret := _m.Called(ctx, body)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *Column
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ColumnUpdateRequest) (*Column, error)); ok {
		return rf(ctx, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ColumnUpdateRequest) *Column); ok {
		r0 = rf(ctx, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Column)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ColumnUpdateRequest) error); ok {
		r1 = rf(ctx, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockColumnService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockColumnService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - body ColumnUpdateRequest
func (_e *MockColumnService_Expecter) Update(ctx interface{}, body interface{}) *MockColumnService_Update_Call {
	return &MockColumnService_Update_Call{Call: _e.mock.On("Update", ctx, body)}
}

func (_c *MockColumnService_Update_Call) Run(run func(ctx context.Context, body ColumnUpdateRequest)) *MockColumnService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ColumnUpdateRequest))
	})
	return _c
}

func (_c *MockColumnService_Update_Call) Return(_a0 *Column, _a1 error) *MockColumnService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockColumnService_Update_Call) RunAndReturn(run func(context.Context, ColumnUpdateRequest) (*Column, error)) *MockColumnService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockColumnService creates a new instance of MockColumnService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockColumnService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockColumnService {
	mock := &MockColumnService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
