apiVersion: v1
kind: Service
metadata:
  name: {{ include "scrumlr-fullname" .Values.livequery }}
  labels: 
    {{- include "selectorLabels" .Values.livequery | nindent 6 }}
    {{- include "labels" . | nindent 6 }}
spec:
  ports:
    - port: {{ .Values.livequery.port }}
      targetPort: {{ .Values.livequery.hostPort }}
      protocol: TCP
  selector:
    {{- include "selectorLabels" .Values.livequery | nindent 6 }}