// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package events

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"scrumlr.io/server/websocket"
)

// NewMockSessionRequestConnectionManager creates a new instance of MockSessionRequestConnectionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRequestConnectionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRequestConnectionManager {
	mock := &MockSessionRequestConnectionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRequestConnectionManager is an autogenerated mock type for the SessionRequestConnectionManager type
type MockSessionRequestConnectionManager struct {
	mock.Mock
}

type MockSessionRequestConnectionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRequestConnectionManager) EXPECT() *MockSessionRequestConnectionManager_Expecter {
	return &MockSessionRequestConnectionManager_Expecter{mock: &_m.Mock}
}

// Register provides a mock function for the type MockSessionRequestConnectionManager
func (_mock *MockSessionRequestConnectionManager) Register(ctx context.Context, connection websocket.Connection, boardId uuid.UUID, userId uuid.UUID) error {
	ret := _mock.Called(ctx, connection, boardId, userId)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, websocket.Connection, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, connection, boardId, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRequestConnectionManager_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockSessionRequestConnectionManager_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - connection websocket.Connection
//   - boardId uuid.UUID
//   - userId uuid.UUID
func (_e *MockSessionRequestConnectionManager_Expecter) Register(ctx any, connection any, boardId any, userId any) *MockSessionRequestConnectionManager_Register_Call {
	return &MockSessionRequestConnectionManager_Register_Call{Call: _e.mock.On("Register", ctx, connection, boardId, userId)}
}

func (_c *MockSessionRequestConnectionManager_Register_Call) Run(run func(ctx context.Context, connection websocket.Connection, boardId uuid.UUID, userId uuid.UUID)) *MockSessionRequestConnectionManager_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 websocket.Connection
		if args[1] != nil {
			arg1 = args[1].(websocket.Connection)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSessionRequestConnectionManager_Register_Call) Return(err error) *MockSessionRequestConnectionManager_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRequestConnectionManager_Register_Call) RunAndReturn(run func(ctx context.Context, connection websocket.Connection, boardId uuid.UUID, userId uuid.UUID) error) *MockSessionRequestConnectionManager_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Unregister provides a mock function for the type MockSessionRequestConnectionManager
func (_mock *MockSessionRequestConnectionManager) Unregister(ctx context.Context, boardId uuid.UUID, userId uuid.UUID) {
	_mock.Called(ctx, boardId, userId)
	return
}

// MockSessionRequestConnectionManager_Unregister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unregister'
type MockSessionRequestConnectionManager_Unregister_Call struct {
	*mock.Call
}

// Unregister is a helper method to define mock.On call
//   - ctx context.Context
//   - boardId uuid.UUID
//   - userId uuid.UUID
func (_e *MockSessionRequestConnectionManager_Expecter) Unregister(ctx any, boardId any, userId any) *MockSessionRequestConnectionManager_Unregister_Call {
	return &MockSessionRequestConnectionManager_Unregister_Call{Call: _e.mock.On("Unregister", ctx, boardId, userId)}
}

func (_c *MockSessionRequestConnectionManager_Unregister_Call) Run(run func(ctx context.Context, boardId uuid.UUID, userId uuid.UUID)) *MockSessionRequestConnectionManager_Unregister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRequestConnectionManager_Unregister_Call) Return() *MockSessionRequestConnectionManager_Unregister_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionRequestConnectionManager_Unregister_Call) RunAndReturn(run func(ctx context.Context, boardId uuid.UUID, userId uuid.UUID)) *MockSessionRequestConnectionManager_Unregister_Call {
	_c.Run(run)
	return _c
}
