apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrumlr-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrumlr-database
  template:
    metadata:
      labels: 
        app: scrumlr-database
    spec:
      containers:
        - name: scrumlr-database
          image: mongo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
      restartPolicy: Always