---
version: 2
updates:
  # Client
  - package-ecosystem: npm
    allow:
      - dependency-type: "direct"
    directory: "/"
    schedule: &schedule
      interval: daily
    cooldown: &cooldown
      default-days: 10
    open-pull-requests-limit: 10
    target-branch: "main"
    labels: &dependency_labels
      - "Dependencies"
    versioning-strategy: increase
    commit-message:
      prefix: "yarn"
      include: "scope"

  # Server
  - package-ecosystem: "gomod"
    directory: "/server/src"
    allow:
      - dependency-type: "direct"
    schedule: *schedule
    cooldown: *cooldown
    open-pull-requests-limit: 10
    target-branch: "main"
    labels: *dependency_labels
    commit-message: &go_commit_message
      prefix: "go"
      include: "scope"
    groups: &go_groups
      redis:
        patterns:
          - "github.com/redis/go-redis/*"
      bun:
        patterns:
          - "github.com/uptrace/bun"
          - "github.com/uptrace/bun/*"
      testcontainers:
        patterns:
          - "github.com/testcontainers/*"
      go/opentelemetry:
        patterns:
          - "go.opentelemetry.io/otel"
          - "go.opentelemetry.io/otel/*"
          - "go.opentelemetry.io/contrib/*"

  # Server e2e tests, which requires src modules indirectly
  - package-ecosystem: "gomod"
    directory: "/server/e2e-tests"
    allow:
      - dependency-type: "all"
    schedule: *schedule
    cooldown: *cooldown
    open-pull-requests-limit: 10
    target-branch: "main"
    labels: *dependency_labels
    commit-message: *go_commit_message
    groups: *go_groups
