---
changelog:
  exclude:
    authors:
      - dependabot[bot]
  categories:
    - title: "✨ Features"
      labels:
        - "feat"
    - title: "🐛 Fixes"
      labels:
        - "fix"
    - title: "🔄 Refactoring"
      labels:
        - "refactor"
    - title: 🌐 Localization
      labels:
        - "feat(i18n)"
    - title: "⚙️ Chores"
      labels:
        - "chore"
    - title: "📚 Docs"
      labels:
        - "docs"
    - title: "🤖 CI"
      labels:
        - "ci"
    - title: "No label match"
      labels:
        - "*"
