// Code generated by mockery v2.53.0. DO NOT EDIT.

package health

import mock "github.com/stretchr/testify/mock"

// MockHealthDatabase is an autogenerated mock type for the HealthDatabase type
type MockHealthDatabase struct {
	mock.Mock
}

type MockHealthDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthDatabase) EXPECT() *MockHealthDatabase_Expecter {
	return &MockHealthDatabase_Expecter{mock: &_m.Mock}
}

// IsHealthy provides a mock function with no fields
func (_m *MockHealthDatabase) IsHealthy() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsHealthy")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockHealthDatabase_IsHealthy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsHealthy'
type MockHealthDatabase_IsHealthy_Call struct {
	*mock.Call
}

// IsHealthy is a helper method to define mock.On call
func (_e *MockHealthDatabase_Expecter) IsHealthy() *MockHealthDatabase_IsHealthy_Call {
	return &MockHealthDatabase_IsHealthy_Call{Call: _e.mock.On("IsHealthy")}
}

func (_c *MockHealthDatabase_IsHealthy_Call) Run(run func()) *MockHealthDatabase_IsHealthy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthDatabase_IsHealthy_Call) Return(_a0 bool) *MockHealthDatabase_IsHealthy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthDatabase_IsHealthy_Call) RunAndReturn(run func() bool) *MockHealthDatabase_IsHealthy_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthDatabase creates a new instance of MockHealthDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthDatabase {
	mock := &MockHealthDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
