// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package health

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHealthApi creates a new instance of MockHealthApi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthApi(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthApi {
	mock := &MockHealthApi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHealthApi is an autogenerated mock type for the HealthApi type
type MockHealthApi struct {
	mock.Mock
}

type MockHealthApi_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthApi) EXPECT() *MockHealthApi_Expecter {
	return &MockHealthApi_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type MockHealthApi
func (_mock *MockHealthApi) Check(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockHealthApi_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockHealthApi_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHealthApi_Expecter) Check(w any, r any) *MockHealthApi_Check_Call {
	return &MockHealthApi_Check_Call{Call: _e.mock.On("Check", w, r)}
}

func (_c *MockHealthApi_Check_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHealthApi_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHealthApi_Check_Call) Return() *MockHealthApi_Check_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthApi_Check_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockHealthApi_Check_Call {
	_c.Run(run)
	return _c
}
