// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package feedback

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFeedbackApi creates a new instance of MockFeedbackApi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeedbackApi(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeedbackApi {
	mock := &MockFeedbackApi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFeedbackApi is an autogenerated mock type for the FeedbackApi type
type MockFeedbackApi struct {
	mock.Mock
}

type MockFeedbackApi_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeedbackApi) EXPECT() *MockFeedbackApi_Expecter {
	return &MockFeedbackApi_Expecter{mock: &_m.Mock}
}

// CreateFeedback provides a mock function for the type MockFeedbackApi
func (_mock *MockFeedbackApi) CreateFeedback(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockFeedbackApi_CreateFeedback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFeedback'
type MockFeedbackApi_CreateFeedback_Call struct {
	*mock.Call
}

// CreateFeedback is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockFeedbackApi_Expecter) CreateFeedback(w any, r any) *MockFeedbackApi_CreateFeedback_Call {
	return &MockFeedbackApi_CreateFeedback_Call{Call: _e.mock.On("CreateFeedback", w, r)}
}

func (_c *MockFeedbackApi_CreateFeedback_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockFeedbackApi_CreateFeedback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFeedbackApi_CreateFeedback_Call) Return() *MockFeedbackApi_CreateFeedback_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFeedbackApi_CreateFeedback_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockFeedbackApi_CreateFeedback_Call {
	_c.Run(run)
	return _c
}
