// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package encoder

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPasswordEncoder creates a new instance of MockPasswordEncoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordEncoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordEncoder {
	mock := &MockPasswordEncoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordEncoder is an autogenerated mock type for the PasswordEncoder type
type MockPasswordEncoder struct {
	mock.Mock
}

type MockPasswordEncoder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordEncoder) EXPECT() *MockPasswordEncoder_Expecter {
	return &MockPasswordEncoder_Expecter{mock: &_m.Mock}
}

// Encode provides a mock function for the type MockPasswordEncoder
func (_mock *MockPasswordEncoder) Encode(password string) (*string, *string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 *string
	var r1 *string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (*string, *string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *string); ok {
		r0 = returnFunc(password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *string); ok {
		r1 = returnFunc(password)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(password)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPasswordEncoder_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type MockPasswordEncoder_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - password string
func (_e *MockPasswordEncoder_Expecter) Encode(password any) *MockPasswordEncoder_Encode_Call {
	return &MockPasswordEncoder_Encode_Call{Call: _e.mock.On("Encode", password)}
}

func (_c *MockPasswordEncoder_Encode_Call) Run(run func(password string)) *MockPasswordEncoder_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPasswordEncoder_Encode_Call) Return(s *string, s1 *string, err error) *MockPasswordEncoder_Encode_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *MockPasswordEncoder_Encode_Call) RunAndReturn(run func(password string) (*string, *string, error)) *MockPasswordEncoder_Encode_Call {
	_c.Call.Return(run)
	return _c
}

// Matches provides a mock function for the type MockPasswordEncoder
func (_mock *MockPasswordEncoder) Matches(password string, encodedPassword string, salt string) (bool, error) {
	ret := _mock.Called(password, encodedPassword, salt)

	if len(ret) == 0 {
		panic("no return value specified for Matches")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (bool, error)); ok {
		return returnFunc(password, encodedPassword, salt)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = returnFunc(password, encodedPassword, salt)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(password, encodedPassword, salt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordEncoder_Matches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Matches'
type MockPasswordEncoder_Matches_Call struct {
	*mock.Call
}

// Matches is a helper method to define mock.On call
//   - password string
//   - encodedPassword string
//   - salt string
func (_e *MockPasswordEncoder_Expecter) Matches(password any, encodedPassword any, salt any) *MockPasswordEncoder_Matches_Call {
	return &MockPasswordEncoder_Matches_Call{Call: _e.mock.On("Matches", password, encodedPassword, salt)}
}

func (_c *MockPasswordEncoder_Matches_Call) Run(run func(password string, encodedPassword string, salt string)) *MockPasswordEncoder_Matches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPasswordEncoder_Matches_Call) Return(b bool, err error) *MockPasswordEncoder_Matches_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPasswordEncoder_Matches_Call) RunAndReturn(run func(password string, encodedPassword string, salt string) (bool, error)) *MockPasswordEncoder_Matches_Call {
	_c.Call.Return(run)
	return _c
}

// UpgradeEncoding provides a mock function for the type MockPasswordEncoder
func (_mock *MockPasswordEncoder) UpgradeEncoding(encodedPassword string) bool {
	ret := _mock.Called(encodedPassword)

	if len(ret) == 0 {
		panic("no return value specified for UpgradeEncoding")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(encodedPassword)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPasswordEncoder_UpgradeEncoding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpgradeEncoding'
type MockPasswordEncoder_UpgradeEncoding_Call struct {
	*mock.Call
}

// UpgradeEncoding is a helper method to define mock.On call
//   - encodedPassword string
func (_e *MockPasswordEncoder_Expecter) UpgradeEncoding(encodedPassword any) *MockPasswordEncoder_UpgradeEncoding_Call {
	return &MockPasswordEncoder_UpgradeEncoding_Call{Call: _e.mock.On("UpgradeEncoding", encodedPassword)}
}

func (_c *MockPasswordEncoder_UpgradeEncoding_Call) Run(run func(encodedPassword string)) *MockPasswordEncoder_UpgradeEncoding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPasswordEncoder_UpgradeEncoding_Call) Return(b bool) *MockPasswordEncoder_UpgradeEncoding_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPasswordEncoder_UpgradeEncoding_Call) RunAndReturn(run func(encodedPassword string) bool) *MockPasswordEncoder_UpgradeEncoding_Call {
	_c.Call.Return(run)
	return _c
}
