// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package websocket

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUpgrader creates a new instance of MockUpgrader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpgrader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpgrader {
	mock := &MockUpgrader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpgrader is an autogenerated mock type for the Upgrader type
type MockUpgrader struct {
	mock.Mock
}

type MockUpgrader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpgrader) EXPECT() *MockUpgrader_Expecter {
	return &MockUpgrader_Expecter{mock: &_m.Mock}
}

// Accept provides a mock function for the type MockUpgrader
func (_mock *MockUpgrader) Accept(w http.ResponseWriter, r *http.Request, checkOrigin bool) (Connection, error) {
	ret := _mock.Called(w, r, checkOrigin)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 Connection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, bool) (Connection, error)); ok {
		return returnFunc(w, r, checkOrigin)
	}
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, bool) Connection); ok {
		r0 = returnFunc(w, r, checkOrigin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Connection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(http.ResponseWriter, *http.Request, bool) error); ok {
		r1 = returnFunc(w, r, checkOrigin)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpgrader_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type MockUpgrader_Accept_Call struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - checkOrigin bool
func (_e *MockUpgrader_Expecter) Accept(w any, r any, checkOrigin any) *MockUpgrader_Accept_Call {
	return &MockUpgrader_Accept_Call{Call: _e.mock.On("Accept", w, r, checkOrigin)}
}

func (_c *MockUpgrader_Accept_Call) Run(run func(w http.ResponseWriter, r *http.Request, checkOrigin bool)) *MockUpgrader_Accept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUpgrader_Accept_Call) Return(connection Connection, err error) *MockUpgrader_Accept_Call {
	_c.Call.Return(connection, err)
	return _c
}

func (_c *MockUpgrader_Accept_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, checkOrigin bool) (Connection, error)) *MockUpgrader_Accept_Call {
	_c.Call.Return(run)
	return _c
}

// IsNormalClose provides a mock function for the type MockUpgrader
func (_mock *MockUpgrader) IsNormalClose(err error) bool {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for IsNormalClose")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(error) bool); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockUpgrader_IsNormalClose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsNormalClose'
type MockUpgrader_IsNormalClose_Call struct {
	*mock.Call
}

// IsNormalClose is a helper method to define mock.On call
//   - err error
func (_e *MockUpgrader_Expecter) IsNormalClose(err any) *MockUpgrader_IsNormalClose_Call {
	return &MockUpgrader_IsNormalClose_Call{Call: _e.mock.On("IsNormalClose", err)}
}

func (_c *MockUpgrader_IsNormalClose_Call) Run(run func(err error)) *MockUpgrader_IsNormalClose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUpgrader_IsNormalClose_Call) Return(b bool) *MockUpgrader_IsNormalClose_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockUpgrader_IsNormalClose_Call) RunAndReturn(run func(err error) bool) *MockUpgrader_IsNormalClose_Call {
	_c.Call.Return(run)
	return _c
}
