apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scrumlr-fullname" .Values.server }}
  labels: 
    {{- include "selectorLabels" .Values.server | nindent 6 }}
    {{- include "labels" . | nindent 6 }}
data:
  SCRUMLR_OPERATION_MODE: "server"
  SCRUMLR_DATABASE_URI: "mongodb://scrumlr-database:27017/dev"
  SCRUMLR_API_HOST: "localhost"
  SCRUMLR_API_PORT: "4000"
  SCRUMLR_SERVE_PRODUCTION_WEBAPP: "false"
  SCRUMLR_CACHE_URL: "redis://scrumlr-cache:6379"
