apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scrumlr-fullname" .Values.server }}
  labels:
    {{- include "selectorLabels" .Values.server | nindent 6 }}
    {{- include "labels" . | nindent 6 }}
data:
  SCRUMLR_SERVER_DATABASE_URL: "postgres://admin:password@scrumlr-database:5432/scrumlr?sslmode=disable"
  SCRUMLR_SERVER_NATS_URL: "nats://@scrumlr-cache:4222"
  SCRUMLR_API_HOST: "localhost"
  SCRUMLR_SERVER_PORT: "8080"
  SCRUMLR_BASE_URL: "http://localhost/api"
