apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "scrumlr-fullname" .Values.server }}
  labels: 
    {{- include "selectorLabels" .Values.server | nindent 6 }}
    {{- include "labels" . | nindent 6 }}
spec:
  rules:
  - http:
      paths:
      - path:  {{ .Values.server.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "scrumlr-fullname" .Values.server }}
            port:
              number: {{ .Values.server.port }}
