apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scrumlr-fullname" .Values.server }}
  labels: 
    {{- include "selectorLabels" .Values.server | nindent 6 }}
    {{- include "labels" . | nindent 6 }}
data:
  SCRUMLR_API_MASTER_KEY: bWFzdGVyS2V5
