apiVersion: v1
kind: Service
metadata:
  name: {{ include "scrumlr-fullname" .Values.server }}
  labels: 
    {{- include "selectorLabels" .Values.server | nindent 6 }}
    {{- include "labels" . | nindent 6 }}
spec:
  ports:
    - port: 4000 
      targetPort: server 
      protocol: TCP
  selector:
    {{- include "selectorLabels" .Values.server | nindent 6 }}
