---
apiVersion: v1
kind: Service
metadata:
  name: scrumlr-backend
  namespace: scrumlr
spec:
  selector:
    app: scrumlr
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrumlr-deployment
  namespace: scrumlr
  labels:
    app: scrumlr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scrumlr
  template:
    metadata:
      labels:
        app: scrumlr
    spec:
      containers:
        - name: scrumlr
          image: ghcr.io/inovex/scrumlr.io/scrumlr-server:sha-71c6812
          args:
            - "/app/main"
            - "-disable-check-origin"
          resources:
            requests:
              cpu: "200m"
              memory: "200Mi"
            limits:
              cpu: "400m"
              memory: "400Mi"
          startupProbe:
            httpGet:
              path: /api/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
          env:
            - name: SCRUMLR_SERVER_PORT
              value: "8080"
            - name: SCRUMLR_SERVER_NATS_URL
              value: nats://nats:4222
            - name: SCRUMLR_AUTH_CALLBACK_HOST
              value: "https://${SCRUMLR_DEPLOYMENT_DOMAIN}"
            - name: SCRUMLR_UNSAFE_PRIVATE_KEY
              value: "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAArAAAABNlY2RzYS\n1zaGEyLW5pc3RwNTIxAAAACG5pc3RwNTIxAAAAhQQA6zgG1vHujjrCagonqdAohU76Vk1p\nxFbQg9cP79qORmU61AaWgF34vl4ZYe7TIVxlE+7cGDwGpVldAZANsfDKuMYAERIXnA0XYg\nrTKIzdzYqrDVqK1cA9EstRNRFUn3xqKLP7yYBgSfntCNEKziZDPxAMNGr9mnxCpEWnsnN4\nH1Hua30AAAEYHuFx2B7hcdgAAAATZWNkc2Etc2hhMi1uaXN0cDUyMQAAAAhuaXN0cDUyMQ\nAAAIUEAOs4Btbx7o46wmoKJ6nQKIVO+lZNacRW0IPXD+/ajkZlOtQGloBd+L5eGWHu0yFc\nZRPu3Bg8BqVZXQGQDbHwyrjGABESF5wNF2IK0yiM3c2Kqw1aitXAPRLLUTURVJ98aiiz+8\nmAYEn57QjRCs4mQz8QDDRq/Zp8QqRFp7JzeB9R7mt9AAAAQQftU8WU2CCqtVvTp6Nc5GBd\nDVB34c0DszsSU9HWuURDJdJDZ6wYm9bSnJwgyKilBsNets+sDHzpjSCwUcCT9csOAAAAGW\nNocmlzdGlhbmRyZWllckBjZHJlaWVybmIBAg==\n-----END OPENSSH PRIVATE KEY-----\n"
            - name: SCRUMLR_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: scrumlr-ecdsa-key
                  key: private_key
            - name: SCRUMLR_SERVER_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgresql-creds
                  key: url
            # - name: SCRUMLR_AUTH_GOOGLE_CLIENT_ID
            #   valueFrom:
            #     secretKeyRef:
            #       name: scrumlr-secrets
            #       key: GOOGLE_CLIENT_ID
            # - name: SCRUMLR_AUTH_GOOGLE_CLIENT_SECRET
            #   valueFrom:
            #     secretKeyRef:
            #       name: scrumlr-secrets
            #       key: GOOGLE_CLIENT_SECRET
            # - name: SCRUMLR_AUTH_MICROSOFT_CLIENT_ID
            #   valueFrom:
            #     secretKeyRef:
            #       name: scrumlr-secrets
            #       key: MICROSOFT_CLIENT_ID
            # - name: SCRUMLR_AUTH_MICROSOFT_CLIENT_SECRET
            #   valueFrom:
            #     secretKeyRef:
            #       name: scrumlr-secrets
            #       key: MICROSOFT_CLIENT_SECRET
            # - name: SCRUMLR_FEEDBACK_WEBHOOK_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: scrumlr-secrets
            #       key: WEBHOOK_URL
            - name: SCRUMLR_BASE_PATH
              value: "/api"
          ports:
            - containerPort: 8080