name: 🐛 Bug Report
description: Something is wrong with Scrumlr.
labels: "Unverified Bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug!
  - type: textarea
    id: the-problem
    attributes:
      label: The problem
      description:
        Describe the issue you are experiencing with Scrumlr. Provide a
        clear and concise description of what you were trying to do and what
        happened, along with any error messages you encountered.
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description:
        What browser are you using? (e.g. Chrome, Firefox, Safari, etc.)
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the behavior
      description: Provide steps to reproduce the problem you are experiencing.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain your problem, if applicable.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description:
        Add any other context about the problem you are experiencing here.