// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package draglocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockWebSocketConnection creates a new instance of MockWebSocketConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebSocketConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebSocketConnection {
	mock := &MockWebSocketConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWebSocketConnection is an autogenerated mock type for the WebSocketConnection type
type MockWebSocketConnection struct {
	mock.Mock
}

type MockWebSocketConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebSocketConnection) EXPECT() *MockWebSocketConnection_Expecter {
	return &MockWebSocketConnection_Expecter{mock: &_m.Mock}
}

// WriteJSON provides a mock function for the type MockWebSocketConnection
func (_mock *MockWebSocketConnection) WriteJSON(ctx context.Context, v interface{}) error {
	ret := _mock.Called(ctx, v)

	if len(ret) == 0 {
		panic("no return value specified for WriteJSON")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = returnFunc(ctx, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWebSocketConnection_WriteJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteJSON'
type MockWebSocketConnection_WriteJSON_Call struct {
	*mock.Call
}

// WriteJSON is a helper method to define mock.On call
//   - ctx context.Context
//   - v interface{}
func (_e *MockWebSocketConnection_Expecter) WriteJSON(ctx interface{}, v interface{}) *MockWebSocketConnection_WriteJSON_Call {
	return &MockWebSocketConnection_WriteJSON_Call{Call: _e.mock.On("WriteJSON", ctx, v)}
}

func (_c *MockWebSocketConnection_WriteJSON_Call) Run(run func(ctx context.Context, v interface{})) *MockWebSocketConnection_WriteJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebSocketConnection_WriteJSON_Call) Return(err error) *MockWebSocketConnection_WriteJSON_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWebSocketConnection_WriteJSON_Call) RunAndReturn(run func(ctx context.Context, v interface{}) error) *MockWebSocketConnection_WriteJSON_Call {
	_c.Call.Return(run)
	return _c
}