// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package eventfilter

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"scrumlr.io/server/realtime"
)

// NewMockEventFilter creates a new instance of MockEventFilter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventFilter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventFilter {
	mock := &MockEventFilter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventFilter is an autogenerated mock type for the EventFilter type
type MockEventFilter struct {
	mock.Mock
}

type MockEventFilter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventFilter) EXPECT() *MockEventFilter_Expecter {
	return &MockEventFilter_Expecter{mock: &_m.Mock}
}

// Filter provides a mock function for the type MockEventFilter
func (_mock *MockEventFilter) Filter(ctx context.Context, event *realtime.BoardEvent, boardId uuid.UUID, userId uuid.UUID) *realtime.BoardEvent {
	ret := _mock.Called(ctx, event, boardId, userId)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 *realtime.BoardEvent
	if returnFunc, ok := ret.Get(0).(func(context.Context, *realtime.BoardEvent, uuid.UUID, uuid.UUID) *realtime.BoardEvent); ok {
		r0 = returnFunc(ctx, event, boardId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*realtime.BoardEvent)
		}
	}
	return r0
}

// MockEventFilter_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockEventFilter_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - event *realtime.BoardEvent
//   - boardId uuid.UUID
//   - userId uuid.UUID
func (_e *MockEventFilter_Expecter) Filter(ctx any, event any, boardId any, userId any) *MockEventFilter_Filter_Call {
	return &MockEventFilter_Filter_Call{Call: _e.mock.On("Filter", ctx, event, boardId, userId)}
}

func (_c *MockEventFilter_Filter_Call) Run(run func(ctx context.Context, event *realtime.BoardEvent, boardId uuid.UUID, userId uuid.UUID)) *MockEventFilter_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *realtime.BoardEvent
		if args[1] != nil {
			arg1 = args[1].(*realtime.BoardEvent)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEventFilter_Filter_Call) Return(boardEvent *realtime.BoardEvent) *MockEventFilter_Filter_Call {
	_c.Call.Return(boardEvent)
	return _c
}

func (_c *MockEventFilter_Filter_Call) RunAndReturn(run func(ctx context.Context, event *realtime.BoardEvent, boardId uuid.UUID, userId uuid.UUID) *realtime.BoardEvent) *MockEventFilter_Filter_Call {
	_c.Call.Return(run)
	return _c
}
