// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package eventfilter

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"scrumlr.io/server/realtime"
)

// NewMockFilterRule creates a new instance of MockFilterRule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilterRule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilterRule {
	mock := &MockFilterRule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFilterRule is an autogenerated mock type for the FilterRule type
type MockFilterRule struct {
	mock.Mock
}

type MockFilterRule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilterRule) EXPECT() *MockFilterRule_Expecter {
	return &MockFilterRule_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type MockFilterRule
func (_mock *MockFilterRule) Handle(ctx context.Context, event *realtime.BoardEvent, boardId uuid.UUID, userId uuid.UUID) (*realtime.BoardEvent, error) {
	ret := _mock.Called(ctx, event, boardId, userId)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 *realtime.BoardEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *realtime.BoardEvent, uuid.UUID, uuid.UUID) (*realtime.BoardEvent, error)); ok {
		return returnFunc(ctx, event, boardId, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *realtime.BoardEvent, uuid.UUID, uuid.UUID) *realtime.BoardEvent); ok {
		r0 = returnFunc(ctx, event, boardId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*realtime.BoardEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *realtime.BoardEvent, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, event, boardId, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFilterRule_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockFilterRule_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - event *realtime.BoardEvent
//   - boardId uuid.UUID
//   - userId uuid.UUID
func (_e *MockFilterRule_Expecter) Handle(ctx any, event any, boardId any, userId any) *MockFilterRule_Handle_Call {
	return &MockFilterRule_Handle_Call{Call: _e.mock.On("Handle", ctx, event, boardId, userId)}
}

func (_c *MockFilterRule_Handle_Call) Run(run func(ctx context.Context, event *realtime.BoardEvent, boardId uuid.UUID, userId uuid.UUID)) *MockFilterRule_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *realtime.BoardEvent
		if args[1] != nil {
			arg1 = args[1].(*realtime.BoardEvent)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFilterRule_Handle_Call) Return(boardEvent *realtime.BoardEvent, err error) *MockFilterRule_Handle_Call {
	_c.Call.Return(boardEvent, err)
	return _c
}

func (_c *MockFilterRule_Handle_Call) RunAndReturn(run func(ctx context.Context, event *realtime.BoardEvent, boardId uuid.UUID, userId uuid.UUID) (*realtime.BoardEvent, error)) *MockFilterRule_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// Supports provides a mock function for the type MockFilterRule
func (_mock *MockFilterRule) Supports(ctx context.Context, eventType realtime.BoardEventType) bool {
	ret := _mock.Called(ctx, eventType)

	if len(ret) == 0 {
		panic("no return value specified for Supports")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, realtime.BoardEventType) bool); ok {
		r0 = returnFunc(ctx, eventType)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockFilterRule_Supports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Supports'
type MockFilterRule_Supports_Call struct {
	*mock.Call
}

// Supports is a helper method to define mock.On call
//   - ctx context.Context
//   - eventType realtime.BoardEventType
func (_e *MockFilterRule_Expecter) Supports(ctx any, eventType any) *MockFilterRule_Supports_Call {
	return &MockFilterRule_Supports_Call{Call: _e.mock.On("Supports", ctx, eventType)}
}

func (_c *MockFilterRule_Supports_Call) Run(run func(ctx context.Context, eventType realtime.BoardEventType)) *MockFilterRule_Supports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 realtime.BoardEventType
		if args[1] != nil {
			arg1 = args[1].(realtime.BoardEventType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFilterRule_Supports_Call) Return(b bool) *MockFilterRule_Supports_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockFilterRule_Supports_Call) RunAndReturn(run func(ctx context.Context, eventType realtime.BoardEventType) bool) *MockFilterRule_Supports_Call {
	_c.Call.Return(run)
	return _c
}
