---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres

---
apiVersion: v1
kind: Namespace
metadata:
  name: nats

---
apiVersion: v1
kind: Namespace
metadata:
  name: scrumlr

---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
