port = 8080
nats = "nats://localhost:4222"
redis-address = ""
redis-username = ""          
redis-password = ""         
insecure = true         
unsafe-key = ""             
key = ""            
database = "postgres://admin:supersecret@localhost:5432/scrumlr?sslmode=disable"                 
base-path = "/"                   
auth-callback-host = ""          
auth-google-client-id = ""       
auth-google-client-secret = ""   
auth-github-client-id = ""       
auth-github-client-secret = ""  
auth-microsoft-client-id = ""
auth-microsoft-client-secret = ""
auth-azure-ad-tenant-id = ""
auth-azure-ad-client-id = ""
auth-azure-ad-client-secret = ""
auth-apple-client-id = ""
auth-apple-client-secret = ""   
verbose = true
disable-check-origin = true        
feedback-webhook-url = "" 