// Code generated by mockery v2.52.3. DO NOT EDIT.

package columntemplates

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockColumnTemplateDatabase is an autogenerated mock type for the ColumnTemplateDatabase type
type MockColumnTemplateDatabase struct {
	mock.Mock
}

type MockColumnTemplateDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockColumnTemplateDatabase) EXPECT() *MockColumnTemplateDatabase_Expecter {
	return &MockColumnTemplateDatabase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: column
func (_m *MockColumnTemplateDatabase) Create(column DatabaseColumnTemplateInsert) (DatabaseColumnTemplate, error) {
	ret := _m.Called(column)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 DatabaseColumnTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(DatabaseColumnTemplateInsert) (DatabaseColumnTemplate, error)); ok {
		return rf(column)
	}
	if rf, ok := ret.Get(0).(func(DatabaseColumnTemplateInsert) DatabaseColumnTemplate); ok {
		r0 = rf(column)
	} else {
		r0 = ret.Get(0).(DatabaseColumnTemplate)
	}

	if rf, ok := ret.Get(1).(func(DatabaseColumnTemplateInsert) error); ok {
		r1 = rf(column)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockColumnTemplateDatabase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockColumnTemplateDatabase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - column DatabaseColumnTemplateInsert
func (_e *MockColumnTemplateDatabase_Expecter) Create(column interface{}) *MockColumnTemplateDatabase_Create_Call {
	return &MockColumnTemplateDatabase_Create_Call{Call: _e.mock.On("Create", column)}
}

func (_c *MockColumnTemplateDatabase_Create_Call) Run(run func(column DatabaseColumnTemplateInsert)) *MockColumnTemplateDatabase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(DatabaseColumnTemplateInsert))
	})
	return _c
}

func (_c *MockColumnTemplateDatabase_Create_Call) Return(_a0 DatabaseColumnTemplate, _a1 error) *MockColumnTemplateDatabase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockColumnTemplateDatabase_Create_Call) RunAndReturn(run func(DatabaseColumnTemplateInsert) (DatabaseColumnTemplate, error)) *MockColumnTemplateDatabase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: board, column, user
func (_m *MockColumnTemplateDatabase) Delete(board uuid.UUID, column uuid.UUID, user uuid.UUID) error {
	ret := _m.Called(board, column, user)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(board, column, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockColumnTemplateDatabase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockColumnTemplateDatabase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - board uuid.UUID
//   - column uuid.UUID
//   - user uuid.UUID
func (_e *MockColumnTemplateDatabase_Expecter) Delete(board interface{}, column interface{}, user interface{}) *MockColumnTemplateDatabase_Delete_Call {
	return &MockColumnTemplateDatabase_Delete_Call{Call: _e.mock.On("Delete", board, column, user)}
}

func (_c *MockColumnTemplateDatabase_Delete_Call) Run(run func(board uuid.UUID, column uuid.UUID, user uuid.UUID)) *MockColumnTemplateDatabase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockColumnTemplateDatabase_Delete_Call) Return(_a0 error) *MockColumnTemplateDatabase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockColumnTemplateDatabase_Delete_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID, uuid.UUID) error) *MockColumnTemplateDatabase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: board, id
func (_m *MockColumnTemplateDatabase) Get(board uuid.UUID, id uuid.UUID) (DatabaseColumnTemplate, error) {
	ret := _m.Called(board, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 DatabaseColumnTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (DatabaseColumnTemplate, error)); ok {
		return rf(board, id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) DatabaseColumnTemplate); ok {
		r0 = rf(board, id)
	} else {
		r0 = ret.Get(0).(DatabaseColumnTemplate)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(board, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockColumnTemplateDatabase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockColumnTemplateDatabase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - board uuid.UUID
//   - id uuid.UUID
func (_e *MockColumnTemplateDatabase_Expecter) Get(board interface{}, id interface{}) *MockColumnTemplateDatabase_Get_Call {
	return &MockColumnTemplateDatabase_Get_Call{Call: _e.mock.On("Get", board, id)}
}

func (_c *MockColumnTemplateDatabase_Get_Call) Run(run func(board uuid.UUID, id uuid.UUID)) *MockColumnTemplateDatabase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockColumnTemplateDatabase_Get_Call) Return(_a0 DatabaseColumnTemplate, _a1 error) *MockColumnTemplateDatabase_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockColumnTemplateDatabase_Get_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID) (DatabaseColumnTemplate, error)) *MockColumnTemplateDatabase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: board
func (_m *MockColumnTemplateDatabase) GetAll(board uuid.UUID) ([]DatabaseColumnTemplate, error) {
	ret := _m.Called(board)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []DatabaseColumnTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]DatabaseColumnTemplate, error)); ok {
		return rf(board)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []DatabaseColumnTemplate); ok {
		r0 = rf(board)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DatabaseColumnTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(board)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockColumnTemplateDatabase_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockColumnTemplateDatabase_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - board uuid.UUID
func (_e *MockColumnTemplateDatabase_Expecter) GetAll(board interface{}) *MockColumnTemplateDatabase_GetAll_Call {
	return &MockColumnTemplateDatabase_GetAll_Call{Call: _e.mock.On("GetAll", board)}
}

func (_c *MockColumnTemplateDatabase_GetAll_Call) Run(run func(board uuid.UUID)) *MockColumnTemplateDatabase_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockColumnTemplateDatabase_GetAll_Call) Return(_a0 []DatabaseColumnTemplate, _a1 error) *MockColumnTemplateDatabase_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockColumnTemplateDatabase_GetAll_Call) RunAndReturn(run func(uuid.UUID) ([]DatabaseColumnTemplate, error)) *MockColumnTemplateDatabase_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: column
func (_m *MockColumnTemplateDatabase) Update(column DatabaseColumnTemplateUpdate) (DatabaseColumnTemplate, error) {
	ret := _m.Called(column)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 DatabaseColumnTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(DatabaseColumnTemplateUpdate) (DatabaseColumnTemplate, error)); ok {
		return rf(column)
	}
	if rf, ok := ret.Get(0).(func(DatabaseColumnTemplateUpdate) DatabaseColumnTemplate); ok {
		r0 = rf(column)
	} else {
		r0 = ret.Get(0).(DatabaseColumnTemplate)
	}

	if rf, ok := ret.Get(1).(func(DatabaseColumnTemplateUpdate) error); ok {
		r1 = rf(column)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockColumnTemplateDatabase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockColumnTemplateDatabase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - column DatabaseColumnTemplateUpdate
func (_e *MockColumnTemplateDatabase_Expecter) Update(column interface{}) *MockColumnTemplateDatabase_Update_Call {
	return &MockColumnTemplateDatabase_Update_Call{Call: _e.mock.On("Update", column)}
}

func (_c *MockColumnTemplateDatabase_Update_Call) Run(run func(column DatabaseColumnTemplateUpdate)) *MockColumnTemplateDatabase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(DatabaseColumnTemplateUpdate))
	})
	return _c
}

func (_c *MockColumnTemplateDatabase_Update_Call) Return(_a0 DatabaseColumnTemplate, _a1 error) *MockColumnTemplateDatabase_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockColumnTemplateDatabase_Update_Call) RunAndReturn(run func(DatabaseColumnTemplateUpdate) (DatabaseColumnTemplate, error)) *MockColumnTemplateDatabase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockColumnTemplateDatabase creates a new instance of MockColumnTemplateDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockColumnTemplateDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockColumnTemplateDatabase {
	mock := &MockColumnTemplateDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
