FROM node:lts-alpine

COPY . .
RUN yarn install

ENV SCRUMLR_OPERATION_MODE=server
ENV SCRUMLR_DATABASE_URI=mongodb://scrumlr-database:27017/dev
ENV SCRUMLR_API_HOST=localhost
ENV SCRUMLR_API_PORT=4000
ENV SCRUMLR_API_MASTER_KEY=masterKey
ENV SCRUMLR_SERVE_PRODUCTION_WEBAPP=false
ENV SCRUMLR_CACHE_URL=redis://scrumlr-cache:6379

ENTRYPOINT yarn start