apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  scrumlr_operation_mode: "server"
  scrumlr_database_uri: "mongodb://scrumlr-database:27017/dev"
  scrumlr_api_host: "localhost"
  scrumlr_api_port: "4000"
  scrumlr_serve_production_webapp: "false"
  scrumlr_cache_url: "redis://scrumlr-cache:6379"