// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sessionrequests

import (
	"net/http"

	"scrumlr.io/server/websocket"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionRequestWebsocket creates a new instance of MockSessionRequestWebsocket. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRequestWebsocket(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRequestWebsocket {
	mock := &MockSessionRequestWebsocket{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRequestWebsocket is an autogenerated mock type for the Websocket type
type MockSessionRequestWebsocket struct {
	mock.Mock
}

type MockSessionRequestWebsocket_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRequestWebsocket) EXPECT() *MockSessionRequestWebsocket_Expecter {
	return &MockSessionRequestWebsocket_Expecter{mock: &_m.Mock}
}

// OpenSocket provides a mock function for the type MockSessionRequestWebsocket
func (_mock *MockSessionRequestWebsocket) OpenSocket(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockSessionRequestWebsocket_OpenSocket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenSocket'
type MockSessionRequestWebsocket_OpenSocket_Call struct {
	*mock.Call
}

// OpenSocket is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockSessionRequestWebsocket_Expecter) OpenSocket(w interface{}, r interface{}) *MockSessionRequestWebsocket_OpenSocket_Call {
	return &MockSessionRequestWebsocket_OpenSocket_Call{Call: _e.mock.On("OpenSocket", w, r)}
}

func (_c *MockSessionRequestWebsocket_OpenSocket_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockSessionRequestWebsocket_OpenSocket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRequestWebsocket_OpenSocket_Call) Return() *MockSessionRequestWebsocket_OpenSocket_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionRequestWebsocket_OpenSocket_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockSessionRequestWebsocket_OpenSocket_Call {
	_c.Run(run)
	return _c
}

// closeSocket provides a mock function for the type MockSessionRequestWebsocket
func (_mock *MockSessionRequestWebsocket) closeSocket(conn websocket.Connection) {
	_mock.Called(conn)
	return
}

// MockSessionRequestWebsocket_closeSocket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'closeSocket'
type MockSessionRequestWebsocket_closeSocket_Call struct {
	*mock.Call
}

// closeSocket is a helper method to define mock.On call
//   - conn technical_helper.Connection
func (_e *MockSessionRequestWebsocket_Expecter) closeSocket(conn interface{}) *MockSessionRequestWebsocket_closeSocket_Call {
	return &MockSessionRequestWebsocket_closeSocket_Call{Call: _e.mock.On("closeSocket", conn)}
}

func (_c *MockSessionRequestWebsocket_closeSocket_Call) Run(run func(conn websocket.Connection)) *MockSessionRequestWebsocket_closeSocket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 websocket.Connection
		if args[0] != nil {
			arg0 = args[0].(websocket.Connection)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionRequestWebsocket_closeSocket_Call) Return() *MockSessionRequestWebsocket_closeSocket_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionRequestWebsocket_closeSocket_Call) RunAndReturn(run func(conn websocket.Connection)) *MockSessionRequestWebsocket_closeSocket_Call {
	_c.Run(run)
	return _c
}

// listenOnBoardSessionRequest provides a mock function for the type MockSessionRequestWebsocket
func (_mock *MockSessionRequestWebsocket) listenOnBoardSessionRequest(boardID uuid.UUID, userID uuid.UUID, conn websocket.Connection) {
	_mock.Called(boardID, userID, conn)
	return
}

// MockSessionRequestWebsocket_listenOnBoardSessionRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'listenOnBoardSessionRequest'
type MockSessionRequestWebsocket_listenOnBoardSessionRequest_Call struct {
	*mock.Call
}

// listenOnBoardSessionRequest is a helper method to define mock.On call
//   - boardID uuid.UUID
//   - userID uuid.UUID
//   - conn technical_helper.Connection
func (_e *MockSessionRequestWebsocket_Expecter) listenOnBoardSessionRequest(boardID interface{}, userID interface{}, conn interface{}) *MockSessionRequestWebsocket_listenOnBoardSessionRequest_Call {
	return &MockSessionRequestWebsocket_listenOnBoardSessionRequest_Call{Call: _e.mock.On("listenOnBoardSessionRequest", boardID, userID, conn)}
}

func (_c *MockSessionRequestWebsocket_listenOnBoardSessionRequest_Call) Run(run func(boardID uuid.UUID, userID uuid.UUID, conn websocket.Connection)) *MockSessionRequestWebsocket_listenOnBoardSessionRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 websocket.Connection
		if args[2] != nil {
			arg2 = args[2].(websocket.Connection)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRequestWebsocket_listenOnBoardSessionRequest_Call) Return() *MockSessionRequestWebsocket_listenOnBoardSessionRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionRequestWebsocket_listenOnBoardSessionRequest_Call) RunAndReturn(run func(boardID uuid.UUID, userID uuid.UUID, conn websocket.Connection)) *MockSessionRequestWebsocket_listenOnBoardSessionRequest_Call {
	_c.Run(run)
	return _c
}
