// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sessionrequests

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionRequestDatabase creates a new instance of MockSessionRequestDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRequestDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRequestDatabase {
	mock := &MockSessionRequestDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRequestDatabase is an autogenerated mock type for the SessionRequestDatabase type
type MockSessionRequestDatabase struct {
	mock.Mock
}

type MockSessionRequestDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRequestDatabase) EXPECT() *MockSessionRequestDatabase_Expecter {
	return &MockSessionRequestDatabase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSessionRequestDatabase
func (_mock *MockSessionRequestDatabase) Create(ctx context.Context, request DatabaseBoardSessionRequestInsert) (DatabaseBoardSessionRequest, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 DatabaseBoardSessionRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, DatabaseBoardSessionRequestInsert) (DatabaseBoardSessionRequest, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, DatabaseBoardSessionRequestInsert) DatabaseBoardSessionRequest); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(DatabaseBoardSessionRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, DatabaseBoardSessionRequestInsert) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRequestDatabase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionRequestDatabase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - request DatabaseBoardSessionRequestInsert
func (_e *MockSessionRequestDatabase_Expecter) Create(ctx interface{}, request interface{}) *MockSessionRequestDatabase_Create_Call {
	return &MockSessionRequestDatabase_Create_Call{Call: _e.mock.On("Create", ctx, request)}
}

func (_c *MockSessionRequestDatabase_Create_Call) Run(run func(ctx context.Context, request DatabaseBoardSessionRequestInsert)) *MockSessionRequestDatabase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 DatabaseBoardSessionRequestInsert
		if args[1] != nil {
			arg1 = args[1].(DatabaseBoardSessionRequestInsert)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRequestDatabase_Create_Call) Return(databaseBoardSessionRequest DatabaseBoardSessionRequest, err error) *MockSessionRequestDatabase_Create_Call {
	_c.Call.Return(databaseBoardSessionRequest, err)
	return _c
}

func (_c *MockSessionRequestDatabase_Create_Call) RunAndReturn(run func(ctx context.Context, request DatabaseBoardSessionRequestInsert) (DatabaseBoardSessionRequest, error)) *MockSessionRequestDatabase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockSessionRequestDatabase
func (_mock *MockSessionRequestDatabase) Exists(ctx context.Context, board uuid.UUID, user uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, board, user)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, board, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, board, user)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, board, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRequestDatabase_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockSessionRequestDatabase_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - board uuid.UUID
//   - user uuid.UUID
func (_e *MockSessionRequestDatabase_Expecter) Exists(ctx interface{}, board interface{}, user interface{}) *MockSessionRequestDatabase_Exists_Call {
	return &MockSessionRequestDatabase_Exists_Call{Call: _e.mock.On("Exists", ctx, board, user)}
}

func (_c *MockSessionRequestDatabase_Exists_Call) Run(run func(ctx context.Context, board uuid.UUID, user uuid.UUID)) *MockSessionRequestDatabase_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRequestDatabase_Exists_Call) Return(b bool, err error) *MockSessionRequestDatabase_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSessionRequestDatabase_Exists_Call) RunAndReturn(run func(ctx context.Context, board uuid.UUID, user uuid.UUID) (bool, error)) *MockSessionRequestDatabase_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockSessionRequestDatabase
func (_mock *MockSessionRequestDatabase) Get(ctx context.Context, board uuid.UUID, user uuid.UUID) (DatabaseBoardSessionRequest, error) {
	ret := _mock.Called(ctx, board, user)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 DatabaseBoardSessionRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (DatabaseBoardSessionRequest, error)); ok {
		return returnFunc(ctx, board, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) DatabaseBoardSessionRequest); ok {
		r0 = returnFunc(ctx, board, user)
	} else {
		r0 = ret.Get(0).(DatabaseBoardSessionRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, board, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRequestDatabase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionRequestDatabase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - board uuid.UUID
//   - user uuid.UUID
func (_e *MockSessionRequestDatabase_Expecter) Get(ctx interface{}, board interface{}, user interface{}) *MockSessionRequestDatabase_Get_Call {
	return &MockSessionRequestDatabase_Get_Call{Call: _e.mock.On("Get", ctx, board, user)}
}

func (_c *MockSessionRequestDatabase_Get_Call) Run(run func(ctx context.Context, board uuid.UUID, user uuid.UUID)) *MockSessionRequestDatabase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRequestDatabase_Get_Call) Return(databaseBoardSessionRequest DatabaseBoardSessionRequest, err error) *MockSessionRequestDatabase_Get_Call {
	_c.Call.Return(databaseBoardSessionRequest, err)
	return _c
}

func (_c *MockSessionRequestDatabase_Get_Call) RunAndReturn(run func(ctx context.Context, board uuid.UUID, user uuid.UUID) (DatabaseBoardSessionRequest, error)) *MockSessionRequestDatabase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockSessionRequestDatabase
func (_mock *MockSessionRequestDatabase) GetAll(ctx context.Context, board uuid.UUID, status ...RequestStatus) ([]DatabaseBoardSessionRequest, error) {
	var tmpRet mock.Arguments
	if len(status) > 0 {
		tmpRet = _mock.Called(ctx, board, status)
	} else {
		tmpRet = _mock.Called(ctx, board)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []DatabaseBoardSessionRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...RequestStatus) ([]DatabaseBoardSessionRequest, error)); ok {
		return returnFunc(ctx, board, status...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...RequestStatus) []DatabaseBoardSessionRequest); ok {
		r0 = returnFunc(ctx, board, status...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DatabaseBoardSessionRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...RequestStatus) error); ok {
		r1 = returnFunc(ctx, board, status...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRequestDatabase_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockSessionRequestDatabase_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - board uuid.UUID
//   - status ...RequestStatus
func (_e *MockSessionRequestDatabase_Expecter) GetAll(ctx interface{}, board interface{}, status ...interface{}) *MockSessionRequestDatabase_GetAll_Call {
	return &MockSessionRequestDatabase_GetAll_Call{Call: _e.mock.On("GetAll",
		append([]interface{}{ctx, board}, status...)...)}
}

func (_c *MockSessionRequestDatabase_GetAll_Call) Run(run func(ctx context.Context, board uuid.UUID, status ...RequestStatus)) *MockSessionRequestDatabase_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []RequestStatus
		var variadicArgs []RequestStatus
		if len(args) > 2 {
			variadicArgs = args[2].([]RequestStatus)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSessionRequestDatabase_GetAll_Call) Return(databaseBoardSessionRequests []DatabaseBoardSessionRequest, err error) *MockSessionRequestDatabase_GetAll_Call {
	_c.Call.Return(databaseBoardSessionRequests, err)
	return _c
}

func (_c *MockSessionRequestDatabase_GetAll_Call) RunAndReturn(run func(ctx context.Context, board uuid.UUID, status ...RequestStatus) ([]DatabaseBoardSessionRequest, error)) *MockSessionRequestDatabase_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSessionRequestDatabase
func (_mock *MockSessionRequestDatabase) Update(ctx context.Context, update DatabaseBoardSessionRequestUpdate) (DatabaseBoardSessionRequest, error) {
	ret := _mock.Called(ctx, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 DatabaseBoardSessionRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, DatabaseBoardSessionRequestUpdate) (DatabaseBoardSessionRequest, error)); ok {
		return returnFunc(ctx, update)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, DatabaseBoardSessionRequestUpdate) DatabaseBoardSessionRequest); ok {
		r0 = returnFunc(ctx, update)
	} else {
		r0 = ret.Get(0).(DatabaseBoardSessionRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, DatabaseBoardSessionRequestUpdate) error); ok {
		r1 = returnFunc(ctx, update)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRequestDatabase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSessionRequestDatabase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - update DatabaseBoardSessionRequestUpdate
func (_e *MockSessionRequestDatabase_Expecter) Update(ctx interface{}, update interface{}) *MockSessionRequestDatabase_Update_Call {
	return &MockSessionRequestDatabase_Update_Call{Call: _e.mock.On("Update", ctx, update)}
}

func (_c *MockSessionRequestDatabase_Update_Call) Run(run func(ctx context.Context, update DatabaseBoardSessionRequestUpdate)) *MockSessionRequestDatabase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 DatabaseBoardSessionRequestUpdate
		if args[1] != nil {
			arg1 = args[1].(DatabaseBoardSessionRequestUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRequestDatabase_Update_Call) Return(databaseBoardSessionRequest DatabaseBoardSessionRequest, err error) *MockSessionRequestDatabase_Update_Call {
	_c.Call.Return(databaseBoardSessionRequest, err)
	return _c
}

func (_c *MockSessionRequestDatabase_Update_Call) RunAndReturn(run func(ctx context.Context, update DatabaseBoardSessionRequestUpdate) (DatabaseBoardSessionRequest, error)) *MockSessionRequestDatabase_Update_Call {
	_c.Call.Return(run)
	return _c
}
