import {createAction} from "@reduxjs/toolkit";
import {Board, BoardActionType} from "./types";
import {Auth} from "../auth";

// export const leaveBoard = createAction("scrumlr.io/leaveBoard");
// export const joinBoard = createAction<{boardId: string; passphrase?: string}>("scrumlr.io/joinBoard");
export const initializeBoard = createAction<{fullBoard: BoardActionType; serverTimeOffset: number; self: Auth}>("scrumlr.io/initializeBoard");
// export const editBoard = createAction<EditBoardRequest>("scrumlr.io/editBoard");
export const updatedBoard = createAction<Board>("scrumlr.io/updatedBoard");
export const updatedBoardTimer = createAction<{board: Board; serverTimeOffset: number}>("scrumlr.io/updatedBoardTimer");
// export const deleteBoard = createAction("scrumlr.io/deleteBoard");
// export const permittedBoardAccess = createAction<string>("scrumlr.io/permittedBoardAccess");
export const rejectedBoardAccess = createAction("scrumlr.io/rejectedBoardAccess");
// export const pendingBoardAccessConfirmation = createAction<{board: string; requestReference: string}>("scrumlr.io/pendingBoardAccessConfirmation");
export const passphraseChallengeRequired = createAction("scrumlr.io/passphraseChallengeRequired");
export const incorrectPassphrase = createAction("scrumlr.io/incorrectPassphrase");
export const tooManyJoinRequests = createAction("scrumlr.io/tooManyJoinRequests");
export const bannedFromBoard = createAction("scrumlr.io/bannedFromBoard");
// export const setTimer = createAction<number>("scrumlr.io/setTimer");
// export const cancelTimer = createAction("scrumlr.io/cancelTimer");
// export const incrementTimer = createAction("scrumlr.io/incrementTimer");
