---

issuer: 'http://oidc.localhost:5556/dex'

storage:
  type: memory

web:
  http: '0.0.0.0:5556'

staticClients:
  - id: ''
    redirectURIs:
      - 'http://localhost:8080/api/login/oidc/callback'
    name: ''
    secret: ''

enablePasswordDB: true
staticPasswords:
  - email: ''
    # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
    hash: ''
    username: ''
    userID: ''


