// Code generated by mockery v2.53.0. DO NOT EDIT.

package notes

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "scrumlr.io/server/common/dto"

	uuid "github.com/google/uuid"
)

// MockNotesService is an autogenerated mock type for the NotesService type
type MockNotesService struct {
	mock.Mock
}

type MockNotesService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotesService) EXPECT() *MockNotesService_Expecter {
	return &MockNotesService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, body
func (_m *MockNotesService) Create(ctx context.Context, body NoteCreateRequest) (*Note, error) {
	ret := _m.Called(ctx, body)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, NoteCreateRequest) (*Note, error)); ok {
		return rf(ctx, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, NoteCreateRequest) *Note); ok {
		r0 = rf(ctx, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, NoteCreateRequest) error); ok {
		r1 = rf(ctx, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotesService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockNotesService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - body NoteCreateRequest
func (_e *MockNotesService_Expecter) Create(ctx interface{}, body interface{}) *MockNotesService_Create_Call {
	return &MockNotesService_Create_Call{Call: _e.mock.On("Create", ctx, body)}
}

func (_c *MockNotesService_Create_Call) Run(run func(ctx context.Context, body NoteCreateRequest)) *MockNotesService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(NoteCreateRequest))
	})
	return _c
}

func (_c *MockNotesService_Create_Call) Return(_a0 *Note, _a1 error) *MockNotesService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotesService_Create_Call) RunAndReturn(run func(context.Context, NoteCreateRequest) (*Note, error)) *MockNotesService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, body, noteID, votes
func (_m *MockNotesService) Delete(ctx context.Context, body NoteDeleteRequest, noteID uuid.UUID, votes []*dto.Vote) error {
	ret := _m.Called(ctx, body, noteID, votes)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, NoteDeleteRequest, uuid.UUID, []*dto.Vote) error); ok {
		r0 = rf(ctx, body, noteID, votes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotesService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockNotesService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - body NoteDeleteRequest
//   - noteID uuid.UUID
//   - votes []*dto.Vote
func (_e *MockNotesService_Expecter) Delete(ctx interface{}, body interface{}, noteID interface{}, votes interface{}) *MockNotesService_Delete_Call {
	return &MockNotesService_Delete_Call{Call: _e.mock.On("Delete", ctx, body, noteID, votes)}
}

func (_c *MockNotesService_Delete_Call) Run(run func(ctx context.Context, body NoteDeleteRequest, noteID uuid.UUID, votes []*dto.Vote)) *MockNotesService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(NoteDeleteRequest), args[2].(uuid.UUID), args[3].([]*dto.Vote))
	})
	return _c
}

func (_c *MockNotesService_Delete_Call) Return(_a0 error) *MockNotesService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotesService_Delete_Call) RunAndReturn(run func(context.Context, NoteDeleteRequest, uuid.UUID, []*dto.Vote) error) *MockNotesService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockNotesService) Get(ctx context.Context, id uuid.UUID) (*Note, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*Note, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *Note); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotesService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockNotesService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockNotesService_Expecter) Get(ctx interface{}, id interface{}) *MockNotesService_Get_Call {
	return &MockNotesService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockNotesService_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockNotesService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockNotesService_Get_Call) Return(_a0 *Note, _a1 error) *MockNotesService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotesService_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*Note, error)) *MockNotesService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetStack provides a mock function with given fields: ctx, id
func (_m *MockNotesService) GetStack(ctx context.Context, id uuid.UUID) ([]*Note, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetStack")
	}

	var r0 []*Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*Note, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*Note); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotesService_GetStack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStack'
type MockNotesService_GetStack_Call struct {
	*mock.Call
}

// GetStack is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockNotesService_Expecter) GetStack(ctx interface{}, id interface{}) *MockNotesService_GetStack_Call {
	return &MockNotesService_GetStack_Call{Call: _e.mock.On("GetStack", ctx, id)}
}

func (_c *MockNotesService_GetStack_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockNotesService_GetStack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockNotesService_GetStack_Call) Return(_a0 []*Note, _a1 error) *MockNotesService_GetStack_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotesService_GetStack_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*Note, error)) *MockNotesService_GetStack_Call {
	_c.Call.Return(run)
	return _c
}

// Import provides a mock function with given fields: ctx, body
func (_m *MockNotesService) Import(ctx context.Context, body NoteImportRequest) (*Note, error) {
	ret := _m.Called(ctx, body)

	if len(ret) == 0 {
		panic("no return value specified for Import")
	}

	var r0 *Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, NoteImportRequest) (*Note, error)); ok {
		return rf(ctx, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, NoteImportRequest) *Note); ok {
		r0 = rf(ctx, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, NoteImportRequest) error); ok {
		r1 = rf(ctx, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotesService_Import_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Import'
type MockNotesService_Import_Call struct {
	*mock.Call
}

// Import is a helper method to define mock.On call
//   - ctx context.Context
//   - body NoteImportRequest
func (_e *MockNotesService_Expecter) Import(ctx interface{}, body interface{}) *MockNotesService_Import_Call {
	return &MockNotesService_Import_Call{Call: _e.mock.On("Import", ctx, body)}
}

func (_c *MockNotesService_Import_Call) Run(run func(ctx context.Context, body NoteImportRequest)) *MockNotesService_Import_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(NoteImportRequest))
	})
	return _c
}

func (_c *MockNotesService_Import_Call) Return(_a0 *Note, _a1 error) *MockNotesService_Import_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotesService_Import_Call) RunAndReturn(run func(context.Context, NoteImportRequest) (*Note, error)) *MockNotesService_Import_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, id
func (_m *MockNotesService) List(ctx context.Context, id uuid.UUID) ([]*Note, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*Note, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*Note); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotesService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockNotesService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockNotesService_Expecter) List(ctx interface{}, id interface{}) *MockNotesService_List_Call {
	return &MockNotesService_List_Call{Call: _e.mock.On("List", ctx, id)}
}

func (_c *MockNotesService_List_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockNotesService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockNotesService_List_Call) Return(_a0 []*Note, _a1 error) *MockNotesService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotesService_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*Note, error)) *MockNotesService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, body
func (_m *MockNotesService) Update(ctx context.Context, body NoteUpdateRequest) (*Note, error) {
	ret := _m.Called(ctx, body)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, NoteUpdateRequest) (*Note, error)); ok {
		return rf(ctx, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, NoteUpdateRequest) *Note); ok {
		r0 = rf(ctx, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, NoteUpdateRequest) error); ok {
		r1 = rf(ctx, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotesService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockNotesService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - body NoteUpdateRequest
func (_e *MockNotesService_Expecter) Update(ctx interface{}, body interface{}) *MockNotesService_Update_Call {
	return &MockNotesService_Update_Call{Call: _e.mock.On("Update", ctx, body)}
}

func (_c *MockNotesService_Update_Call) Run(run func(ctx context.Context, body NoteUpdateRequest)) *MockNotesService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(NoteUpdateRequest))
	})
	return _c
}

func (_c *MockNotesService_Update_Call) Return(_a0 *Note, _a1 error) *MockNotesService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotesService_Update_Call) RunAndReturn(run func(context.Context, NoteUpdateRequest) (*Note, error)) *MockNotesService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotesService creates a new instance of MockNotesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotesService {
	mock := &MockNotesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
