// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package notes

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"scrumlr.io/server/realtime"
)

// NewMockNotesService creates a new instance of MockNotesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotesService {
	mock := &MockNotesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotesService is an autogenerated mock type for the NotesService type
type MockNotesService struct {
	mock.Mock
}

type MockNotesService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotesService) EXPECT() *MockNotesService_Expecter {
	return &MockNotesService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockNotesService
func (_mock *MockNotesService) Create(ctx context.Context, body NoteCreateRequest) (*Note, error) {
	ret := _mock.Called(ctx, body)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *Note
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, NoteCreateRequest) (*Note, error)); ok {
		return returnFunc(ctx, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, NoteCreateRequest) *Note); ok {
		r0 = returnFunc(ctx, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Note)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, NoteCreateRequest) error); ok {
		r1 = returnFunc(ctx, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockNotesService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - body NoteCreateRequest
func (_e *MockNotesService_Expecter) Create(ctx interface{}, body interface{}) *MockNotesService_Create_Call {
	return &MockNotesService_Create_Call{Call: _e.mock.On("Create", ctx, body)}
}

func (_c *MockNotesService_Create_Call) Run(run func(ctx context.Context, body NoteCreateRequest)) *MockNotesService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 NoteCreateRequest
		if args[1] != nil {
			arg1 = args[1].(NoteCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotesService_Create_Call) Return(note *Note, err error) *MockNotesService_Create_Call {
	_c.Call.Return(note, err)
	return _c
}

func (_c *MockNotesService_Create_Call) RunAndReturn(run func(ctx context.Context, body NoteCreateRequest) (*Note, error)) *MockNotesService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockNotesService
func (_mock *MockNotesService) Delete(ctx context.Context, body NoteDeleteRequest, id uuid.UUID) error {
	ret := _mock.Called(ctx, body, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, NoteDeleteRequest, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, body, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotesService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockNotesService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - body NoteDeleteRequest
//   - id uuid.UUID
func (_e *MockNotesService_Expecter) Delete(ctx interface{}, body interface{}, id interface{}) *MockNotesService_Delete_Call {
	return &MockNotesService_Delete_Call{Call: _e.mock.On("Delete", ctx, body, id)}
}

func (_c *MockNotesService_Delete_Call) Run(run func(ctx context.Context, body NoteDeleteRequest, id uuid.UUID)) *MockNotesService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 NoteDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(NoteDeleteRequest)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotesService_Delete_Call) Return(err error) *MockNotesService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotesService_Delete_Call) RunAndReturn(run func(ctx context.Context, body NoteDeleteRequest, id uuid.UUID) error) *MockNotesService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockNotesService
func (_mock *MockNotesService) Get(ctx context.Context, id uuid.UUID) (*Note, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *Note
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*Note, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *Note); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Note)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockNotesService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockNotesService_Expecter) Get(ctx interface{}, id interface{}) *MockNotesService_Get_Call {
	return &MockNotesService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockNotesService_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockNotesService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotesService_Get_Call) Return(note *Note, err error) *MockNotesService_Get_Call {
	_c.Call.Return(note, err)
	return _c
}

func (_c *MockNotesService_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*Note, error)) *MockNotesService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockNotesService
func (_mock *MockNotesService) GetAll(ctx context.Context, id uuid.UUID, columns ...uuid.UUID) ([]*Note, error) {
	var tmpRet mock.Arguments
	if len(columns) > 0 {
		tmpRet = _mock.Called(ctx, id, columns)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*Note
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...uuid.UUID) ([]*Note, error)); ok {
		return returnFunc(ctx, id, columns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...uuid.UUID) []*Note); ok {
		r0 = returnFunc(ctx, id, columns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Note)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, columns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockNotesService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - columns ...uuid.UUID
func (_e *MockNotesService_Expecter) GetAll(ctx interface{}, id interface{}, columns ...interface{}) *MockNotesService_GetAll_Call {
	return &MockNotesService_GetAll_Call{Call: _e.mock.On("GetAll",
		append([]interface{}{ctx, id}, columns...)...)}
}

func (_c *MockNotesService_GetAll_Call) Run(run func(ctx context.Context, id uuid.UUID, columns ...uuid.UUID)) *MockNotesService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []uuid.UUID
		var variadicArgs []uuid.UUID
		if len(args) > 2 {
			variadicArgs = args[2].([]uuid.UUID)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockNotesService_GetAll_Call) Return(notes []*Note, err error) *MockNotesService_GetAll_Call {
	_c.Call.Return(notes, err)
	return _c
}

func (_c *MockNotesService_GetAll_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, columns ...uuid.UUID) ([]*Note, error)) *MockNotesService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetStack provides a mock function for the type MockNotesService
func (_mock *MockNotesService) GetStack(ctx context.Context, note uuid.UUID) ([]*Note, error) {
	ret := _mock.Called(ctx, note)

	if len(ret) == 0 {
		panic("no return value specified for GetStack")
	}

	var r0 []*Note
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*Note, error)); ok {
		return returnFunc(ctx, note)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*Note); ok {
		r0 = returnFunc(ctx, note)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Note)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, note)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesService_GetStack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStack'
type MockNotesService_GetStack_Call struct {
	*mock.Call
}

// GetStack is a helper method to define mock.On call
//   - ctx context.Context
//   - note uuid.UUID
func (_e *MockNotesService_Expecter) GetStack(ctx interface{}, note interface{}) *MockNotesService_GetStack_Call {
	return &MockNotesService_GetStack_Call{Call: _e.mock.On("GetStack", ctx, note)}
}

func (_c *MockNotesService_GetStack_Call) Run(run func(ctx context.Context, note uuid.UUID)) *MockNotesService_GetStack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotesService_GetStack_Call) Return(notes []*Note, err error) *MockNotesService_GetStack_Call {
	_c.Call.Return(notes, err)
	return _c
}

func (_c *MockNotesService_GetStack_Call) RunAndReturn(run func(ctx context.Context, note uuid.UUID) ([]*Note, error)) *MockNotesService_GetStack_Call {
	_c.Call.Return(run)
	return _c
}

// Import provides a mock function for the type MockNotesService
func (_mock *MockNotesService) Import(ctx context.Context, body NoteImportRequest) (*Note, error) {
	ret := _mock.Called(ctx, body)

	if len(ret) == 0 {
		panic("no return value specified for Import")
	}

	var r0 *Note
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, NoteImportRequest) (*Note, error)); ok {
		return returnFunc(ctx, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, NoteImportRequest) *Note); ok {
		r0 = returnFunc(ctx, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Note)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, NoteImportRequest) error); ok {
		r1 = returnFunc(ctx, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesService_Import_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Import'
type MockNotesService_Import_Call struct {
	*mock.Call
}

// Import is a helper method to define mock.On call
//   - ctx context.Context
//   - body NoteImportRequest
func (_e *MockNotesService_Expecter) Import(ctx interface{}, body interface{}) *MockNotesService_Import_Call {
	return &MockNotesService_Import_Call{Call: _e.mock.On("Import", ctx, body)}
}

func (_c *MockNotesService_Import_Call) Run(run func(ctx context.Context, body NoteImportRequest)) *MockNotesService_Import_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 NoteImportRequest
		if args[1] != nil {
			arg1 = args[1].(NoteImportRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotesService_Import_Call) Return(note *Note, err error) *MockNotesService_Import_Call {
	_c.Call.Return(note, err)
	return _c
}

func (_c *MockNotesService_Import_Call) RunAndReturn(run func(ctx context.Context, body NoteImportRequest) (*Note, error)) *MockNotesService_Import_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockNotesService
func (_mock *MockNotesService) Update(ctx context.Context, body NoteUpdateRequest) (*Note, error) {
	ret := _mock.Called(ctx, body)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *Note
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, NoteUpdateRequest) (*Note, error)); ok {
		return returnFunc(ctx, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, NoteUpdateRequest) *Note); ok {
		r0 = returnFunc(ctx, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Note)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, NoteUpdateRequest) error); ok {
		r1 = returnFunc(ctx, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockNotesService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - body NoteUpdateRequest
func (_e *MockNotesService_Expecter) Update(ctx interface{}, body interface{}) *MockNotesService_Update_Call {
	return &MockNotesService_Update_Call{Call: _e.mock.On("Update", ctx, body)}
}

func (_c *MockNotesService_Update_Call) Run(run func(ctx context.Context, body NoteUpdateRequest)) *MockNotesService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 NoteUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(NoteUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotesService_Update_Call) Return(note *Note, err error) *MockNotesService_Update_Call {
	_c.Call.Return(note, err)
	return _c
}

func (_c *MockNotesService_Update_Call) RunAndReturn(run func(ctx context.Context, body NoteUpdateRequest) (*Note, error)) *MockNotesService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEvent provides a mock function for the type MockNotesService
func (_mock *MockNotesService) UpdateEvent(event *realtime.BoardEvent, userId uuid.UUID, isMod bool, boardId uuid.UUID, columnVisabilities []ColumnVisability, showNotesOfOtherUsers bool, showAuthors bool) (*realtime.BoardEvent, bool) {
	ret := _mock.Called(event, userId, isMod, boardId, columnVisabilities, showNotesOfOtherUsers, showAuthors)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEvent")
	}

	var r0 *realtime.BoardEvent
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(*realtime.BoardEvent, uuid.UUID, bool, uuid.UUID, []ColumnVisability, bool, bool) (*realtime.BoardEvent, bool)); ok {
		return returnFunc(event, userId, isMod, boardId, columnVisabilities, showNotesOfOtherUsers, showAuthors)
	}
	if returnFunc, ok := ret.Get(0).(func(*realtime.BoardEvent, uuid.UUID, bool, uuid.UUID, []ColumnVisability, bool, bool) *realtime.BoardEvent); ok {
		r0 = returnFunc(event, userId, isMod, boardId, columnVisabilities, showNotesOfOtherUsers, showAuthors)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*realtime.BoardEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*realtime.BoardEvent, uuid.UUID, bool, uuid.UUID, []ColumnVisability, bool, bool) bool); ok {
		r1 = returnFunc(event, userId, isMod, boardId, columnVisabilities, showNotesOfOtherUsers, showAuthors)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockNotesService_UpdateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEvent'
type MockNotesService_UpdateEvent_Call struct {
	*mock.Call
}

// UpdateEvent is a helper method to define mock.On call
//   - event *realtime.BoardEvent
//   - userId uuid.UUID
//   - isMod bool
//   - boardId uuid.UUID
//   - columnVisabilities []ColumnVisability
//   - showNotesOfOtherUsers bool
//   - showAuthors bool
func (_e *MockNotesService_Expecter) UpdateEvent(event interface{}, userId interface{}, isMod interface{}, boardId interface{}, columnVisabilities interface{}, showNotesOfOtherUsers interface{}, showAuthors interface{}) *MockNotesService_UpdateEvent_Call {
	return &MockNotesService_UpdateEvent_Call{Call: _e.mock.On("UpdateEvent", event, userId, isMod, boardId, columnVisabilities, showNotesOfOtherUsers, showAuthors)}
}

func (_c *MockNotesService_UpdateEvent_Call) Run(run func(event *realtime.BoardEvent, userId uuid.UUID, isMod bool, boardId uuid.UUID, columnVisabilities []ColumnVisability, showNotesOfOtherUsers bool, showAuthors bool)) *MockNotesService_UpdateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *realtime.BoardEvent
		if args[0] != nil {
			arg0 = args[0].(*realtime.BoardEvent)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 []ColumnVisability
		if args[4] != nil {
			arg4 = args[4].([]ColumnVisability)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		var arg6 bool
		if args[6] != nil {
			arg6 = args[6].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockNotesService_UpdateEvent_Call) Return(boardEvent *realtime.BoardEvent, b bool) *MockNotesService_UpdateEvent_Call {
	_c.Call.Return(boardEvent, b)
	return _c
}

func (_c *MockNotesService_UpdateEvent_Call) RunAndReturn(run func(event *realtime.BoardEvent, userId uuid.UUID, isMod bool, boardId uuid.UUID, columnVisabilities []ColumnVisability, showNotesOfOtherUsers bool, showAuthors bool) (*realtime.BoardEvent, bool)) *MockNotesService_UpdateEvent_Call {
	_c.Call.Return(run)
	return _c
}
