// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package notes

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotesDatabase creates a new instance of MockNotesDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotesDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotesDatabase {
	mock := &MockNotesDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotesDatabase is an autogenerated mock type for the NotesDatabase type
type MockNotesDatabase struct {
	mock.Mock
}

type MockNotesDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotesDatabase) EXPECT() *MockNotesDatabase_Expecter {
	return &MockNotesDatabase_Expecter{mock: &_m.Mock}
}

// CreateNote provides a mock function for the type MockNotesDatabase
func (_mock *MockNotesDatabase) CreateNote(ctx context.Context, insert DatabaseNoteInsert) (DatabaseNote, error) {
	ret := _mock.Called(ctx, insert)

	if len(ret) == 0 {
		panic("no return value specified for CreateNote")
	}

	var r0 DatabaseNote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, DatabaseNoteInsert) (DatabaseNote, error)); ok {
		return returnFunc(ctx, insert)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, DatabaseNoteInsert) DatabaseNote); ok {
		r0 = returnFunc(ctx, insert)
	} else {
		r0 = ret.Get(0).(DatabaseNote)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, DatabaseNoteInsert) error); ok {
		r1 = returnFunc(ctx, insert)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesDatabase_CreateNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNote'
type MockNotesDatabase_CreateNote_Call struct {
	*mock.Call
}

// CreateNote is a helper method to define mock.On call
//   - ctx context.Context
//   - insert DatabaseNoteInsert
func (_e *MockNotesDatabase_Expecter) CreateNote(ctx interface{}, insert interface{}) *MockNotesDatabase_CreateNote_Call {
	return &MockNotesDatabase_CreateNote_Call{Call: _e.mock.On("CreateNote", ctx, insert)}
}

func (_c *MockNotesDatabase_CreateNote_Call) Run(run func(ctx context.Context, insert DatabaseNoteInsert)) *MockNotesDatabase_CreateNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 DatabaseNoteInsert
		if args[1] != nil {
			arg1 = args[1].(DatabaseNoteInsert)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotesDatabase_CreateNote_Call) Return(databaseNote DatabaseNote, err error) *MockNotesDatabase_CreateNote_Call {
	_c.Call.Return(databaseNote, err)
	return _c
}

func (_c *MockNotesDatabase_CreateNote_Call) RunAndReturn(run func(ctx context.Context, insert DatabaseNoteInsert) (DatabaseNote, error)) *MockNotesDatabase_CreateNote_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNote provides a mock function for the type MockNotesDatabase
func (_mock *MockNotesDatabase) DeleteNote(ctx context.Context, caller uuid.UUID, board uuid.UUID, id uuid.UUID, deleteStack bool) error {
	ret := _mock.Called(ctx, caller, board, id, deleteStack)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNote")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, caller, board, id, deleteStack)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotesDatabase_DeleteNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNote'
type MockNotesDatabase_DeleteNote_Call struct {
	*mock.Call
}

// DeleteNote is a helper method to define mock.On call
//   - ctx context.Context
//   - caller uuid.UUID
//   - board uuid.UUID
//   - id uuid.UUID
//   - deleteStack bool
func (_e *MockNotesDatabase_Expecter) DeleteNote(ctx interface{}, caller interface{}, board interface{}, id interface{}, deleteStack interface{}) *MockNotesDatabase_DeleteNote_Call {
	return &MockNotesDatabase_DeleteNote_Call{Call: _e.mock.On("DeleteNote", ctx, caller, board, id, deleteStack)}
}

func (_c *MockNotesDatabase_DeleteNote_Call) Run(run func(ctx context.Context, caller uuid.UUID, board uuid.UUID, id uuid.UUID, deleteStack bool)) *MockNotesDatabase_DeleteNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockNotesDatabase_DeleteNote_Call) Return(err error) *MockNotesDatabase_DeleteNote_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotesDatabase_DeleteNote_Call) RunAndReturn(run func(ctx context.Context, caller uuid.UUID, board uuid.UUID, id uuid.UUID, deleteStack bool) error) *MockNotesDatabase_DeleteNote_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockNotesDatabase
func (_mock *MockNotesDatabase) Get(ctx context.Context, id uuid.UUID) (DatabaseNote, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 DatabaseNote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (DatabaseNote, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) DatabaseNote); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(DatabaseNote)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesDatabase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockNotesDatabase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockNotesDatabase_Expecter) Get(ctx interface{}, id interface{}) *MockNotesDatabase_Get_Call {
	return &MockNotesDatabase_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockNotesDatabase_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockNotesDatabase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotesDatabase_Get_Call) Return(databaseNote DatabaseNote, err error) *MockNotesDatabase_Get_Call {
	_c.Call.Return(databaseNote, err)
	return _c
}

func (_c *MockNotesDatabase_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (DatabaseNote, error)) *MockNotesDatabase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockNotesDatabase
func (_mock *MockNotesDatabase) GetAll(ctx context.Context, board uuid.UUID, columns ...uuid.UUID) ([]DatabaseNote, error) {
	var tmpRet mock.Arguments
	if len(columns) > 0 {
		tmpRet = _mock.Called(ctx, board, columns)
	} else {
		tmpRet = _mock.Called(ctx, board)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []DatabaseNote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...uuid.UUID) ([]DatabaseNote, error)); ok {
		return returnFunc(ctx, board, columns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...uuid.UUID) []DatabaseNote); ok {
		r0 = returnFunc(ctx, board, columns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DatabaseNote)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...uuid.UUID) error); ok {
		r1 = returnFunc(ctx, board, columns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesDatabase_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockNotesDatabase_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - board uuid.UUID
//   - columns ...uuid.UUID
func (_e *MockNotesDatabase_Expecter) GetAll(ctx interface{}, board interface{}, columns ...interface{}) *MockNotesDatabase_GetAll_Call {
	return &MockNotesDatabase_GetAll_Call{Call: _e.mock.On("GetAll",
		append([]interface{}{ctx, board}, columns...)...)}
}

func (_c *MockNotesDatabase_GetAll_Call) Run(run func(ctx context.Context, board uuid.UUID, columns ...uuid.UUID)) *MockNotesDatabase_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []uuid.UUID
		var variadicArgs []uuid.UUID
		if len(args) > 2 {
			variadicArgs = args[2].([]uuid.UUID)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockNotesDatabase_GetAll_Call) Return(databaseNotes []DatabaseNote, err error) *MockNotesDatabase_GetAll_Call {
	_c.Call.Return(databaseNotes, err)
	return _c
}

func (_c *MockNotesDatabase_GetAll_Call) RunAndReturn(run func(ctx context.Context, board uuid.UUID, columns ...uuid.UUID) ([]DatabaseNote, error)) *MockNotesDatabase_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserAndBoard provides a mock function for the type MockNotesDatabase
func (_mock *MockNotesDatabase) GetByUserAndBoard(ctx context.Context, boardID uuid.UUID, userID uuid.UUID) ([]DatabaseNote, error) {
	ret := _mock.Called(ctx, boardID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserAndBoard")
	}

	var r0 []DatabaseNote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]DatabaseNote, error)); ok {
		return returnFunc(ctx, boardID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []DatabaseNote); ok {
		r0 = returnFunc(ctx, boardID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DatabaseNote)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, boardID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesDatabase_GetByUserAndBoard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserAndBoard'
type MockNotesDatabase_GetByUserAndBoard_Call struct {
	*mock.Call
}

// GetByUserAndBoard is a helper method to define mock.On call
//   - ctx context.Context
//   - boardID uuid.UUID
//   - userID uuid.UUID
func (_e *MockNotesDatabase_Expecter) GetByUserAndBoard(ctx interface{}, boardID interface{}, userID interface{}) *MockNotesDatabase_GetByUserAndBoard_Call {
	return &MockNotesDatabase_GetByUserAndBoard_Call{Call: _e.mock.On("GetByUserAndBoard", ctx, boardID, userID)}
}

func (_c *MockNotesDatabase_GetByUserAndBoard_Call) Run(run func(ctx context.Context, boardID uuid.UUID, userID uuid.UUID)) *MockNotesDatabase_GetByUserAndBoard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotesDatabase_GetByUserAndBoard_Call) Return(databaseNotes []DatabaseNote, err error) *MockNotesDatabase_GetByUserAndBoard_Call {
	_c.Call.Return(databaseNotes, err)
	return _c
}

func (_c *MockNotesDatabase_GetByUserAndBoard_Call) RunAndReturn(run func(ctx context.Context, boardID uuid.UUID, userID uuid.UUID) ([]DatabaseNote, error)) *MockNotesDatabase_GetByUserAndBoard_Call {
	_c.Call.Return(run)
	return _c
}

// GetChildNotes provides a mock function for the type MockNotesDatabase
func (_mock *MockNotesDatabase) GetChildNotes(ctx context.Context, parentNote uuid.UUID) ([]DatabaseNote, error) {
	ret := _mock.Called(ctx, parentNote)

	if len(ret) == 0 {
		panic("no return value specified for GetChildNotes")
	}

	var r0 []DatabaseNote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]DatabaseNote, error)); ok {
		return returnFunc(ctx, parentNote)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []DatabaseNote); ok {
		r0 = returnFunc(ctx, parentNote)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DatabaseNote)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, parentNote)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesDatabase_GetChildNotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChildNotes'
type MockNotesDatabase_GetChildNotes_Call struct {
	*mock.Call
}

// GetChildNotes is a helper method to define mock.On call
//   - ctx context.Context
//   - parentNote uuid.UUID
func (_e *MockNotesDatabase_Expecter) GetChildNotes(ctx interface{}, parentNote interface{}) *MockNotesDatabase_GetChildNotes_Call {
	return &MockNotesDatabase_GetChildNotes_Call{Call: _e.mock.On("GetChildNotes", ctx, parentNote)}
}

func (_c *MockNotesDatabase_GetChildNotes_Call) Run(run func(ctx context.Context, parentNote uuid.UUID)) *MockNotesDatabase_GetChildNotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotesDatabase_GetChildNotes_Call) Return(databaseNotes []DatabaseNote, err error) *MockNotesDatabase_GetChildNotes_Call {
	_c.Call.Return(databaseNotes, err)
	return _c
}

func (_c *MockNotesDatabase_GetChildNotes_Call) RunAndReturn(run func(ctx context.Context, parentNote uuid.UUID) ([]DatabaseNote, error)) *MockNotesDatabase_GetChildNotes_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrecondition provides a mock function for the type MockNotesDatabase
func (_mock *MockNotesDatabase) GetPrecondition(ctx context.Context, id uuid.UUID, board uuid.UUID, caller uuid.UUID) (Precondition, error) {
	ret := _mock.Called(ctx, id, board, caller)

	if len(ret) == 0 {
		panic("no return value specified for GetPrecondition")
	}

	var r0 Precondition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (Precondition, error)); ok {
		return returnFunc(ctx, id, board, caller)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) Precondition); ok {
		r0 = returnFunc(ctx, id, board, caller)
	} else {
		r0 = ret.Get(0).(Precondition)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, board, caller)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesDatabase_GetPrecondition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrecondition'
type MockNotesDatabase_GetPrecondition_Call struct {
	*mock.Call
}

// GetPrecondition is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - board uuid.UUID
//   - caller uuid.UUID
func (_e *MockNotesDatabase_Expecter) GetPrecondition(ctx interface{}, id interface{}, board interface{}, caller interface{}) *MockNotesDatabase_GetPrecondition_Call {
	return &MockNotesDatabase_GetPrecondition_Call{Call: _e.mock.On("GetPrecondition", ctx, id, board, caller)}
}

func (_c *MockNotesDatabase_GetPrecondition_Call) Run(run func(ctx context.Context, id uuid.UUID, board uuid.UUID, caller uuid.UUID)) *MockNotesDatabase_GetPrecondition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockNotesDatabase_GetPrecondition_Call) Return(precondition Precondition, err error) *MockNotesDatabase_GetPrecondition_Call {
	_c.Call.Return(precondition, err)
	return _c
}

func (_c *MockNotesDatabase_GetPrecondition_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, board uuid.UUID, caller uuid.UUID) (Precondition, error)) *MockNotesDatabase_GetPrecondition_Call {
	_c.Call.Return(run)
	return _c
}

// GetStack provides a mock function for the type MockNotesDatabase
func (_mock *MockNotesDatabase) GetStack(ctx context.Context, noteID uuid.UUID) ([]DatabaseNote, error) {
	ret := _mock.Called(ctx, noteID)

	if len(ret) == 0 {
		panic("no return value specified for GetStack")
	}

	var r0 []DatabaseNote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]DatabaseNote, error)); ok {
		return returnFunc(ctx, noteID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []DatabaseNote); ok {
		r0 = returnFunc(ctx, noteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DatabaseNote)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, noteID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesDatabase_GetStack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStack'
type MockNotesDatabase_GetStack_Call struct {
	*mock.Call
}

// GetStack is a helper method to define mock.On call
//   - ctx context.Context
//   - noteID uuid.UUID
func (_e *MockNotesDatabase_Expecter) GetStack(ctx interface{}, noteID interface{}) *MockNotesDatabase_GetStack_Call {
	return &MockNotesDatabase_GetStack_Call{Call: _e.mock.On("GetStack", ctx, noteID)}
}

func (_c *MockNotesDatabase_GetStack_Call) Run(run func(ctx context.Context, noteID uuid.UUID)) *MockNotesDatabase_GetStack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotesDatabase_GetStack_Call) Return(databaseNotes []DatabaseNote, err error) *MockNotesDatabase_GetStack_Call {
	_c.Call.Return(databaseNotes, err)
	return _c
}

func (_c *MockNotesDatabase_GetStack_Call) RunAndReturn(run func(ctx context.Context, noteID uuid.UUID) ([]DatabaseNote, error)) *MockNotesDatabase_GetStack_Call {
	_c.Call.Return(run)
	return _c
}

// ImportNote provides a mock function for the type MockNotesDatabase
func (_mock *MockNotesDatabase) ImportNote(ctx context.Context, insert DatabaseNoteImport) (DatabaseNote, error) {
	ret := _mock.Called(ctx, insert)

	if len(ret) == 0 {
		panic("no return value specified for ImportNote")
	}

	var r0 DatabaseNote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, DatabaseNoteImport) (DatabaseNote, error)); ok {
		return returnFunc(ctx, insert)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, DatabaseNoteImport) DatabaseNote); ok {
		r0 = returnFunc(ctx, insert)
	} else {
		r0 = ret.Get(0).(DatabaseNote)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, DatabaseNoteImport) error); ok {
		r1 = returnFunc(ctx, insert)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesDatabase_ImportNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportNote'
type MockNotesDatabase_ImportNote_Call struct {
	*mock.Call
}

// ImportNote is a helper method to define mock.On call
//   - ctx context.Context
//   - insert DatabaseNoteImport
func (_e *MockNotesDatabase_Expecter) ImportNote(ctx interface{}, insert interface{}) *MockNotesDatabase_ImportNote_Call {
	return &MockNotesDatabase_ImportNote_Call{Call: _e.mock.On("ImportNote", ctx, insert)}
}

func (_c *MockNotesDatabase_ImportNote_Call) Run(run func(ctx context.Context, insert DatabaseNoteImport)) *MockNotesDatabase_ImportNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 DatabaseNoteImport
		if args[1] != nil {
			arg1 = args[1].(DatabaseNoteImport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotesDatabase_ImportNote_Call) Return(databaseNote DatabaseNote, err error) *MockNotesDatabase_ImportNote_Call {
	_c.Call.Return(databaseNote, err)
	return _c
}

func (_c *MockNotesDatabase_ImportNote_Call) RunAndReturn(run func(ctx context.Context, insert DatabaseNoteImport) (DatabaseNote, error)) *MockNotesDatabase_ImportNote_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNote provides a mock function for the type MockNotesDatabase
func (_mock *MockNotesDatabase) UpdateNote(ctx context.Context, caller uuid.UUID, update DatabaseNoteUpdate) (DatabaseNote, error) {
	ret := _mock.Called(ctx, caller, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNote")
	}

	var r0 DatabaseNote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, DatabaseNoteUpdate) (DatabaseNote, error)); ok {
		return returnFunc(ctx, caller, update)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, DatabaseNoteUpdate) DatabaseNote); ok {
		r0 = returnFunc(ctx, caller, update)
	} else {
		r0 = ret.Get(0).(DatabaseNote)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, DatabaseNoteUpdate) error); ok {
		r1 = returnFunc(ctx, caller, update)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotesDatabase_UpdateNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNote'
type MockNotesDatabase_UpdateNote_Call struct {
	*mock.Call
}

// UpdateNote is a helper method to define mock.On call
//   - ctx context.Context
//   - caller uuid.UUID
//   - update DatabaseNoteUpdate
func (_e *MockNotesDatabase_Expecter) UpdateNote(ctx interface{}, caller interface{}, update interface{}) *MockNotesDatabase_UpdateNote_Call {
	return &MockNotesDatabase_UpdateNote_Call{Call: _e.mock.On("UpdateNote", ctx, caller, update)}
}

func (_c *MockNotesDatabase_UpdateNote_Call) Run(run func(ctx context.Context, caller uuid.UUID, update DatabaseNoteUpdate)) *MockNotesDatabase_UpdateNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 DatabaseNoteUpdate
		if args[2] != nil {
			arg2 = args[2].(DatabaseNoteUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotesDatabase_UpdateNote_Call) Return(databaseNote DatabaseNote, err error) *MockNotesDatabase_UpdateNote_Call {
	_c.Call.Return(databaseNote, err)
	return _c
}

func (_c *MockNotesDatabase_UpdateNote_Call) RunAndReturn(run func(ctx context.Context, caller uuid.UUID, update DatabaseNoteUpdate) (DatabaseNote, error)) *MockNotesDatabase_UpdateNote_Call {
	_c.Call.Return(run)
	return _c
}
