{{- if .Values.backend.secretRef }}
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  SCRUMLR_PRIVATE_KEY: {{ .Values.backend.secrets.privateKey | b64enc }}
  SCRUMLR_SERVER_DATABASE_URL: {{ .Values.backend.secrets.databaseUrl | b64enc }}
  {{- range $key, $val := .Values.backend.extraSecrets }}
  {{ $key | upper }}: {{ $val | b64enc }}
  {{- end }}
{{ end }}
