apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-backend
  ports:
    - port: 80
      targetPort: {{ .Values.backend.config.serverPort }}
