hostname: dev.scrumlr.fra.ics.inovex.io
cert:
  enabled: true
  prod: true
  name: scrumlr-cert-main

frontend:
  image: ghcr.io/inovex/scrumlr.io/scrumlr-frontend:latest
  imagePullPolicy: Always 
livequery:
  image: ghcr.io/inovex/scrumlr.io/scrumlr-server:latest
  imagePullPolicy: Always
server:
  image: ghcr.io/inovex/scrumlr.io/scrumlr-server:latest
  imagePullPolicy: Always
dashboard:
  image: ghcr.io/inovex/scrumlr.io/scrumlr-dashboard:latest
  AimagePullPolicy: Always

