// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sessions

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionApi creates a new instance of MockSessionApi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionApi(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionApi {
	mock := &MockSessionApi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionApi is an autogenerated mock type for the SessionApi type
type MockSessionApi struct {
	mock.Mock
}

type MockSessionApi_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionApi) EXPECT() *MockSessionApi_Expecter {
	return &MockSessionApi_Expecter{mock: &_m.Mock}
}

// BoardModeratorContext provides a mock function for the type MockSessionApi
func (_mock *MockSessionApi) BoardModeratorContext(next http.Handler) http.Handler {
	ret := _mock.Called(next)

	if len(ret) == 0 {
		panic("no return value specified for BoardModeratorContext")
	}

	var r0 http.Handler
	if returnFunc, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = returnFunc(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}
	return r0
}

// MockSessionApi_BoardModeratorContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BoardModeratorContext'
type MockSessionApi_BoardModeratorContext_Call struct {
	*mock.Call
}

// BoardModeratorContext is a helper method to define mock.On call
//   - next http.Handler
func (_e *MockSessionApi_Expecter) BoardModeratorContext(next interface{}) *MockSessionApi_BoardModeratorContext_Call {
	return &MockSessionApi_BoardModeratorContext_Call{Call: _e.mock.On("BoardModeratorContext", next)}
}

func (_c *MockSessionApi_BoardModeratorContext_Call) Run(run func(next http.Handler)) *MockSessionApi_BoardModeratorContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.Handler
		if args[0] != nil {
			arg0 = args[0].(http.Handler)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionApi_BoardModeratorContext_Call) Return(handler http.Handler) *MockSessionApi_BoardModeratorContext_Call {
	_c.Call.Return(handler)
	return _c
}

func (_c *MockSessionApi_BoardModeratorContext_Call) RunAndReturn(run func(next http.Handler) http.Handler) *MockSessionApi_BoardModeratorContext_Call {
	_c.Call.Return(run)
	return _c
}

// BoardParticipantContext provides a mock function for the type MockSessionApi
func (_mock *MockSessionApi) BoardParticipantContext(next http.Handler) http.Handler {
	ret := _mock.Called(next)

	if len(ret) == 0 {
		panic("no return value specified for BoardParticipantContext")
	}

	var r0 http.Handler
	if returnFunc, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = returnFunc(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}
	return r0
}

// MockSessionApi_BoardParticipantContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BoardParticipantContext'
type MockSessionApi_BoardParticipantContext_Call struct {
	*mock.Call
}

// BoardParticipantContext is a helper method to define mock.On call
//   - next http.Handler
func (_e *MockSessionApi_Expecter) BoardParticipantContext(next interface{}) *MockSessionApi_BoardParticipantContext_Call {
	return &MockSessionApi_BoardParticipantContext_Call{Call: _e.mock.On("BoardParticipantContext", next)}
}

func (_c *MockSessionApi_BoardParticipantContext_Call) Run(run func(next http.Handler)) *MockSessionApi_BoardParticipantContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.Handler
		if args[0] != nil {
			arg0 = args[0].(http.Handler)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionApi_BoardParticipantContext_Call) Return(handler http.Handler) *MockSessionApi_BoardParticipantContext_Call {
	_c.Call.Return(handler)
	return _c
}

func (_c *MockSessionApi_BoardParticipantContext_Call) RunAndReturn(run func(next http.Handler) http.Handler) *MockSessionApi_BoardParticipantContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetBoardSession provides a mock function for the type MockSessionApi
func (_mock *MockSessionApi) GetBoardSession(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockSessionApi_GetBoardSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBoardSession'
type MockSessionApi_GetBoardSession_Call struct {
	*mock.Call
}

// GetBoardSession is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockSessionApi_Expecter) GetBoardSession(w interface{}, r interface{}) *MockSessionApi_GetBoardSession_Call {
	return &MockSessionApi_GetBoardSession_Call{Call: _e.mock.On("GetBoardSession", w, r)}
}

func (_c *MockSessionApi_GetBoardSession_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockSessionApi_GetBoardSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionApi_GetBoardSession_Call) Return() *MockSessionApi_GetBoardSession_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionApi_GetBoardSession_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockSessionApi_GetBoardSession_Call {
	_c.Run(run)
	return _c
}

// GetBoardSessions provides a mock function for the type MockSessionApi
func (_mock *MockSessionApi) GetBoardSessions(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockSessionApi_GetBoardSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBoardSessions'
type MockSessionApi_GetBoardSessions_Call struct {
	*mock.Call
}

// GetBoardSessions is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockSessionApi_Expecter) GetBoardSessions(w interface{}, r interface{}) *MockSessionApi_GetBoardSessions_Call {
	return &MockSessionApi_GetBoardSessions_Call{Call: _e.mock.On("GetBoardSessions", w, r)}
}

func (_c *MockSessionApi_GetBoardSessions_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockSessionApi_GetBoardSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionApi_GetBoardSessions_Call) Return() *MockSessionApi_GetBoardSessions_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionApi_GetBoardSessions_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockSessionApi_GetBoardSessions_Call {
	_c.Run(run)
	return _c
}

// UpdateBoardSession provides a mock function for the type MockSessionApi
func (_mock *MockSessionApi) UpdateBoardSession(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockSessionApi_UpdateBoardSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBoardSession'
type MockSessionApi_UpdateBoardSession_Call struct {
	*mock.Call
}

// UpdateBoardSession is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockSessionApi_Expecter) UpdateBoardSession(w interface{}, r interface{}) *MockSessionApi_UpdateBoardSession_Call {
	return &MockSessionApi_UpdateBoardSession_Call{Call: _e.mock.On("UpdateBoardSession", w, r)}
}

func (_c *MockSessionApi_UpdateBoardSession_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockSessionApi_UpdateBoardSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionApi_UpdateBoardSession_Call) Return() *MockSessionApi_UpdateBoardSession_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionApi_UpdateBoardSession_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockSessionApi_UpdateBoardSession_Call {
	_c.Run(run)
	return _c
}

// UpdateBoardSessions provides a mock function for the type MockSessionApi
func (_mock *MockSessionApi) UpdateBoardSessions(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockSessionApi_UpdateBoardSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBoardSessions'
type MockSessionApi_UpdateBoardSessions_Call struct {
	*mock.Call
}

// UpdateBoardSessions is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockSessionApi_Expecter) UpdateBoardSessions(w interface{}, r interface{}) *MockSessionApi_UpdateBoardSessions_Call {
	return &MockSessionApi_UpdateBoardSessions_Call{Call: _e.mock.On("UpdateBoardSessions", w, r)}
}

func (_c *MockSessionApi_UpdateBoardSessions_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockSessionApi_UpdateBoardSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionApi_UpdateBoardSessions_Call) Return() *MockSessionApi_UpdateBoardSessions_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionApi_UpdateBoardSessions_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockSessionApi_UpdateBoardSessions_Call {
	_c.Run(run)
	return _c
}
