// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sessions

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionDatabase creates a new instance of MockSessionDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionDatabase {
	mock := &MockSessionDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionDatabase is an autogenerated mock type for the SessionDatabase type
type MockSessionDatabase struct {
	mock.Mock
}

type MockSessionDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionDatabase) EXPECT() *MockSessionDatabase_Expecter {
	return &MockSessionDatabase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSessionDatabase
func (_mock *MockSessionDatabase) Create(ctx context.Context, boardSession DatabaseBoardSessionInsert) (DatabaseBoardSession, error) {
	ret := _mock.Called(ctx, boardSession)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 DatabaseBoardSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, DatabaseBoardSessionInsert) (DatabaseBoardSession, error)); ok {
		return returnFunc(ctx, boardSession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, DatabaseBoardSessionInsert) DatabaseBoardSession); ok {
		r0 = returnFunc(ctx, boardSession)
	} else {
		r0 = ret.Get(0).(DatabaseBoardSession)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, DatabaseBoardSessionInsert) error); ok {
		r1 = returnFunc(ctx, boardSession)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionDatabase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionDatabase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - boardSession DatabaseBoardSessionInsert
func (_e *MockSessionDatabase_Expecter) Create(ctx interface{}, boardSession interface{}) *MockSessionDatabase_Create_Call {
	return &MockSessionDatabase_Create_Call{Call: _e.mock.On("Create", ctx, boardSession)}
}

func (_c *MockSessionDatabase_Create_Call) Run(run func(ctx context.Context, boardSession DatabaseBoardSessionInsert)) *MockSessionDatabase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 DatabaseBoardSessionInsert
		if args[1] != nil {
			arg1 = args[1].(DatabaseBoardSessionInsert)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionDatabase_Create_Call) Return(databaseBoardSession DatabaseBoardSession, err error) *MockSessionDatabase_Create_Call {
	_c.Call.Return(databaseBoardSession, err)
	return _c
}

func (_c *MockSessionDatabase_Create_Call) RunAndReturn(run func(ctx context.Context, boardSession DatabaseBoardSessionInsert) (DatabaseBoardSession, error)) *MockSessionDatabase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockSessionDatabase
func (_mock *MockSessionDatabase) Exists(ctx context.Context, board uuid.UUID, user uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, board, user)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, board, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, board, user)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, board, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionDatabase_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockSessionDatabase_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - board uuid.UUID
//   - user uuid.UUID
func (_e *MockSessionDatabase_Expecter) Exists(ctx interface{}, board interface{}, user interface{}) *MockSessionDatabase_Exists_Call {
	return &MockSessionDatabase_Exists_Call{Call: _e.mock.On("Exists", ctx, board, user)}
}

func (_c *MockSessionDatabase_Exists_Call) Run(run func(ctx context.Context, board uuid.UUID, user uuid.UUID)) *MockSessionDatabase_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionDatabase_Exists_Call) Return(b bool, err error) *MockSessionDatabase_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSessionDatabase_Exists_Call) RunAndReturn(run func(ctx context.Context, board uuid.UUID, user uuid.UUID) (bool, error)) *MockSessionDatabase_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockSessionDatabase
func (_mock *MockSessionDatabase) Get(ctx context.Context, board uuid.UUID, user uuid.UUID) (DatabaseBoardSession, error) {
	ret := _mock.Called(ctx, board, user)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 DatabaseBoardSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (DatabaseBoardSession, error)); ok {
		return returnFunc(ctx, board, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) DatabaseBoardSession); ok {
		r0 = returnFunc(ctx, board, user)
	} else {
		r0 = ret.Get(0).(DatabaseBoardSession)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, board, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionDatabase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionDatabase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - board uuid.UUID
//   - user uuid.UUID
func (_e *MockSessionDatabase_Expecter) Get(ctx interface{}, board interface{}, user interface{}) *MockSessionDatabase_Get_Call {
	return &MockSessionDatabase_Get_Call{Call: _e.mock.On("Get", ctx, board, user)}
}

func (_c *MockSessionDatabase_Get_Call) Run(run func(ctx context.Context, board uuid.UUID, user uuid.UUID)) *MockSessionDatabase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionDatabase_Get_Call) Return(databaseBoardSession DatabaseBoardSession, err error) *MockSessionDatabase_Get_Call {
	_c.Call.Return(databaseBoardSession, err)
	return _c
}

func (_c *MockSessionDatabase_Get_Call) RunAndReturn(run func(ctx context.Context, board uuid.UUID, user uuid.UUID) (DatabaseBoardSession, error)) *MockSessionDatabase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockSessionDatabase
func (_mock *MockSessionDatabase) GetAll(ctx context.Context, board uuid.UUID, filter ...BoardSessionFilter) ([]DatabaseBoardSession, error) {
	var tmpRet mock.Arguments
	if len(filter) > 0 {
		tmpRet = _mock.Called(ctx, board, filter)
	} else {
		tmpRet = _mock.Called(ctx, board)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []DatabaseBoardSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...BoardSessionFilter) ([]DatabaseBoardSession, error)); ok {
		return returnFunc(ctx, board, filter...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...BoardSessionFilter) []DatabaseBoardSession); ok {
		r0 = returnFunc(ctx, board, filter...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DatabaseBoardSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...BoardSessionFilter) error); ok {
		r1 = returnFunc(ctx, board, filter...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionDatabase_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockSessionDatabase_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - board uuid.UUID
//   - filter ...BoardSessionFilter
func (_e *MockSessionDatabase_Expecter) GetAll(ctx interface{}, board interface{}, filter ...interface{}) *MockSessionDatabase_GetAll_Call {
	return &MockSessionDatabase_GetAll_Call{Call: _e.mock.On("GetAll",
		append([]interface{}{ctx, board}, filter...)...)}
}

func (_c *MockSessionDatabase_GetAll_Call) Run(run func(ctx context.Context, board uuid.UUID, filter ...BoardSessionFilter)) *MockSessionDatabase_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []BoardSessionFilter
		var variadicArgs []BoardSessionFilter
		if len(args) > 2 {
			variadicArgs = args[2].([]BoardSessionFilter)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSessionDatabase_GetAll_Call) Return(databaseBoardSessions []DatabaseBoardSession, err error) *MockSessionDatabase_GetAll_Call {
	_c.Call.Return(databaseBoardSessions, err)
	return _c
}

func (_c *MockSessionDatabase_GetAll_Call) RunAndReturn(run func(ctx context.Context, board uuid.UUID, filter ...BoardSessionFilter) ([]DatabaseBoardSession, error)) *MockSessionDatabase_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserBoardSessions provides a mock function for the type MockSessionDatabase
func (_mock *MockSessionDatabase) GetUserBoardSessions(ctx context.Context, user uuid.UUID) ([]DatabaseBoardSession, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBoardSessions")
	}

	var r0 []DatabaseBoardSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]DatabaseBoardSession, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []DatabaseBoardSession); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DatabaseBoardSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionDatabase_GetUserBoardSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBoardSessions'
type MockSessionDatabase_GetUserBoardSessions_Call struct {
	*mock.Call
}

// GetUserBoardSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - user uuid.UUID
func (_e *MockSessionDatabase_Expecter) GetUserBoardSessions(ctx interface{}, user interface{}) *MockSessionDatabase_GetUserBoardSessions_Call {
	return &MockSessionDatabase_GetUserBoardSessions_Call{Call: _e.mock.On("GetUserBoardSessions", ctx, user)}
}

func (_c *MockSessionDatabase_GetUserBoardSessions_Call) Run(run func(ctx context.Context, user uuid.UUID)) *MockSessionDatabase_GetUserBoardSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionDatabase_GetUserBoardSessions_Call) Return(databaseBoardSessions []DatabaseBoardSession, err error) *MockSessionDatabase_GetUserBoardSessions_Call {
	_c.Call.Return(databaseBoardSessions, err)
	return _c
}

func (_c *MockSessionDatabase_GetUserBoardSessions_Call) RunAndReturn(run func(ctx context.Context, user uuid.UUID) ([]DatabaseBoardSession, error)) *MockSessionDatabase_GetUserBoardSessions_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserConnectedBoards provides a mock function for the type MockSessionDatabase
func (_mock *MockSessionDatabase) GetUserConnectedBoards(ctx context.Context, user uuid.UUID) ([]DatabaseBoardSession, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for GetUserConnectedBoards")
	}

	var r0 []DatabaseBoardSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]DatabaseBoardSession, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []DatabaseBoardSession); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DatabaseBoardSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionDatabase_GetUserConnectedBoards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserConnectedBoards'
type MockSessionDatabase_GetUserConnectedBoards_Call struct {
	*mock.Call
}

// GetUserConnectedBoards is a helper method to define mock.On call
//   - ctx context.Context
//   - user uuid.UUID
func (_e *MockSessionDatabase_Expecter) GetUserConnectedBoards(ctx interface{}, user interface{}) *MockSessionDatabase_GetUserConnectedBoards_Call {
	return &MockSessionDatabase_GetUserConnectedBoards_Call{Call: _e.mock.On("GetUserConnectedBoards", ctx, user)}
}

func (_c *MockSessionDatabase_GetUserConnectedBoards_Call) Run(run func(ctx context.Context, user uuid.UUID)) *MockSessionDatabase_GetUserConnectedBoards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionDatabase_GetUserConnectedBoards_Call) Return(databaseBoardSessions []DatabaseBoardSession, err error) *MockSessionDatabase_GetUserConnectedBoards_Call {
	_c.Call.Return(databaseBoardSessions, err)
	return _c
}

func (_c *MockSessionDatabase_GetUserConnectedBoards_Call) RunAndReturn(run func(ctx context.Context, user uuid.UUID) ([]DatabaseBoardSession, error)) *MockSessionDatabase_GetUserConnectedBoards_Call {
	_c.Call.Return(run)
	return _c
}

// IsParticipantBanned provides a mock function for the type MockSessionDatabase
func (_mock *MockSessionDatabase) IsParticipantBanned(ctx context.Context, board uuid.UUID, user uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, board, user)

	if len(ret) == 0 {
		panic("no return value specified for IsParticipantBanned")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, board, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, board, user)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, board, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionDatabase_IsParticipantBanned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsParticipantBanned'
type MockSessionDatabase_IsParticipantBanned_Call struct {
	*mock.Call
}

// IsParticipantBanned is a helper method to define mock.On call
//   - ctx context.Context
//   - board uuid.UUID
//   - user uuid.UUID
func (_e *MockSessionDatabase_Expecter) IsParticipantBanned(ctx interface{}, board interface{}, user interface{}) *MockSessionDatabase_IsParticipantBanned_Call {
	return &MockSessionDatabase_IsParticipantBanned_Call{Call: _e.mock.On("IsParticipantBanned", ctx, board, user)}
}

func (_c *MockSessionDatabase_IsParticipantBanned_Call) Run(run func(ctx context.Context, board uuid.UUID, user uuid.UUID)) *MockSessionDatabase_IsParticipantBanned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionDatabase_IsParticipantBanned_Call) Return(b bool, err error) *MockSessionDatabase_IsParticipantBanned_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSessionDatabase_IsParticipantBanned_Call) RunAndReturn(run func(ctx context.Context, board uuid.UUID, user uuid.UUID) (bool, error)) *MockSessionDatabase_IsParticipantBanned_Call {
	_c.Call.Return(run)
	return _c
}

// ModeratorExists provides a mock function for the type MockSessionDatabase
func (_mock *MockSessionDatabase) ModeratorExists(ctx context.Context, board uuid.UUID, user uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, board, user)

	if len(ret) == 0 {
		panic("no return value specified for ModeratorExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, board, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, board, user)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, board, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionDatabase_ModeratorExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModeratorExists'
type MockSessionDatabase_ModeratorExists_Call struct {
	*mock.Call
}

// ModeratorExists is a helper method to define mock.On call
//   - ctx context.Context
//   - board uuid.UUID
//   - user uuid.UUID
func (_e *MockSessionDatabase_Expecter) ModeratorExists(ctx interface{}, board interface{}, user interface{}) *MockSessionDatabase_ModeratorExists_Call {
	return &MockSessionDatabase_ModeratorExists_Call{Call: _e.mock.On("ModeratorExists", ctx, board, user)}
}

func (_c *MockSessionDatabase_ModeratorExists_Call) Run(run func(ctx context.Context, board uuid.UUID, user uuid.UUID)) *MockSessionDatabase_ModeratorExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionDatabase_ModeratorExists_Call) Return(b bool, err error) *MockSessionDatabase_ModeratorExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSessionDatabase_ModeratorExists_Call) RunAndReturn(run func(ctx context.Context, board uuid.UUID, user uuid.UUID) (bool, error)) *MockSessionDatabase_ModeratorExists_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSessionDatabase
func (_mock *MockSessionDatabase) Update(ctx context.Context, update DatabaseBoardSessionUpdate) (DatabaseBoardSession, error) {
	ret := _mock.Called(ctx, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 DatabaseBoardSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, DatabaseBoardSessionUpdate) (DatabaseBoardSession, error)); ok {
		return returnFunc(ctx, update)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, DatabaseBoardSessionUpdate) DatabaseBoardSession); ok {
		r0 = returnFunc(ctx, update)
	} else {
		r0 = ret.Get(0).(DatabaseBoardSession)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, DatabaseBoardSessionUpdate) error); ok {
		r1 = returnFunc(ctx, update)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionDatabase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSessionDatabase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - update DatabaseBoardSessionUpdate
func (_e *MockSessionDatabase_Expecter) Update(ctx interface{}, update interface{}) *MockSessionDatabase_Update_Call {
	return &MockSessionDatabase_Update_Call{Call: _e.mock.On("Update", ctx, update)}
}

func (_c *MockSessionDatabase_Update_Call) Run(run func(ctx context.Context, update DatabaseBoardSessionUpdate)) *MockSessionDatabase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 DatabaseBoardSessionUpdate
		if args[1] != nil {
			arg1 = args[1].(DatabaseBoardSessionUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionDatabase_Update_Call) Return(databaseBoardSession DatabaseBoardSession, err error) *MockSessionDatabase_Update_Call {
	_c.Call.Return(databaseBoardSession, err)
	return _c
}

func (_c *MockSessionDatabase_Update_Call) RunAndReturn(run func(ctx context.Context, update DatabaseBoardSessionUpdate) (DatabaseBoardSession, error)) *MockSessionDatabase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAll provides a mock function for the type MockSessionDatabase
func (_mock *MockSessionDatabase) UpdateAll(ctx context.Context, update DatabaseBoardSessionUpdate) ([]DatabaseBoardSession, error) {
	ret := _mock.Called(ctx, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAll")
	}

	var r0 []DatabaseBoardSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, DatabaseBoardSessionUpdate) ([]DatabaseBoardSession, error)); ok {
		return returnFunc(ctx, update)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, DatabaseBoardSessionUpdate) []DatabaseBoardSession); ok {
		r0 = returnFunc(ctx, update)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DatabaseBoardSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, DatabaseBoardSessionUpdate) error); ok {
		r1 = returnFunc(ctx, update)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionDatabase_UpdateAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAll'
type MockSessionDatabase_UpdateAll_Call struct {
	*mock.Call
}

// UpdateAll is a helper method to define mock.On call
//   - ctx context.Context
//   - update DatabaseBoardSessionUpdate
func (_e *MockSessionDatabase_Expecter) UpdateAll(ctx interface{}, update interface{}) *MockSessionDatabase_UpdateAll_Call {
	return &MockSessionDatabase_UpdateAll_Call{Call: _e.mock.On("UpdateAll", ctx, update)}
}

func (_c *MockSessionDatabase_UpdateAll_Call) Run(run func(ctx context.Context, update DatabaseBoardSessionUpdate)) *MockSessionDatabase_UpdateAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 DatabaseBoardSessionUpdate
		if args[1] != nil {
			arg1 = args[1].(DatabaseBoardSessionUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionDatabase_UpdateAll_Call) Return(databaseBoardSessions []DatabaseBoardSession, err error) *MockSessionDatabase_UpdateAll_Call {
	_c.Call.Return(databaseBoardSessions, err)
	return _c
}

func (_c *MockSessionDatabase_UpdateAll_Call) RunAndReturn(run func(ctx context.Context, update DatabaseBoardSessionUpdate) ([]DatabaseBoardSession, error)) *MockSessionDatabase_UpdateAll_Call {
	_c.Call.Return(run)
	return _c
}
