// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthProvider creates a new instance of MockAuthProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthProvider {
	mock := &MockAuthProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthProvider is an autogenerated mock type for the AuthProvider type
type MockAuthProvider struct {
	mock.Mock
}

type MockAuthProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthProvider) EXPECT() *MockAuthProvider_Expecter {
	return &MockAuthProvider_Expecter{mock: &_m.Mock}
}

// AuthUrl provides a mock function for the type MockAuthProvider
func (_mock *MockAuthProvider) AuthUrl(state string) string {
	ret := _mock.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for AuthUrl")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(state)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAuthProvider_AuthUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthUrl'
type MockAuthProvider_AuthUrl_Call struct {
	*mock.Call
}

// AuthUrl is a helper method to define mock.On call
//   - state string
func (_e *MockAuthProvider_Expecter) AuthUrl(state any) *MockAuthProvider_AuthUrl_Call {
	return &MockAuthProvider_AuthUrl_Call{Call: _e.mock.On("AuthUrl", state)}
}

func (_c *MockAuthProvider_AuthUrl_Call) Run(run func(state string)) *MockAuthProvider_AuthUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthProvider_AuthUrl_Call) Return(s string) *MockAuthProvider_AuthUrl_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAuthProvider_AuthUrl_Call) RunAndReturn(run func(state string) string) *MockAuthProvider_AuthUrl_Call {
	_c.Call.Return(run)
	return _c
}

// Authenticate provides a mock function for the type MockAuthProvider
func (_mock *MockAuthProvider) Authenticate(ctx context.Context, code string) (*UserInformation, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *UserInformation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*UserInformation, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *UserInformation); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UserInformation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthProvider_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockAuthProvider_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockAuthProvider_Expecter) Authenticate(ctx any, code any) *MockAuthProvider_Authenticate_Call {
	return &MockAuthProvider_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, code)}
}

func (_c *MockAuthProvider_Authenticate_Call) Run(run func(ctx context.Context, code string)) *MockAuthProvider_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthProvider_Authenticate_Call) Return(userInformation *UserInformation, err error) *MockAuthProvider_Authenticate_Call {
	_c.Call.Return(userInformation, err)
	return _c
}

func (_c *MockAuthProvider_Authenticate_Call) RunAndReturn(run func(ctx context.Context, code string) (*UserInformation, error)) *MockAuthProvider_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}
