// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
	"scrumlr.io/server/account"
	"scrumlr.io/server/users"
)

// NewMockAuth creates a new instance of MockAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuth {
	mock := &MockAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuth is an autogenerated mock type for the Auth type
type MockAuth struct {
	mock.Mock
}

type MockAuth_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuth) EXPECT() *MockAuth_Expecter {
	return &MockAuth_Expecter{mock: &_m.Mock}
}

// Authenticator provides a mock function for the type MockAuth
func (_mock *MockAuth) Authenticator() func(http.Handler) http.Handler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Authenticator")
	}

	var r0 func(http.Handler) http.Handler
	if returnFunc, ok := ret.Get(0).(func() func(http.Handler) http.Handler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(http.Handler) http.Handler)
		}
	}
	return r0
}

// MockAuth_Authenticator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticator'
type MockAuth_Authenticator_Call struct {
	*mock.Call
}

// Authenticator is a helper method to define mock.On call
func (_e *MockAuth_Expecter) Authenticator() *MockAuth_Authenticator_Call {
	return &MockAuth_Authenticator_Call{Call: _e.mock.On("Authenticator")}
}

func (_c *MockAuth_Authenticator_Call) Run(run func()) *MockAuth_Authenticator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuth_Authenticator_Call) Return(fn func(http.Handler) http.Handler) *MockAuth_Authenticator_Call {
	_c.Call.Return(fn)
	return _c
}

func (_c *MockAuth_Authenticator_Call) RunAndReturn(run func() func(http.Handler) http.Handler) *MockAuth_Authenticator_Call {
	_c.Call.Return(run)
	return _c
}

// ConfiguredProvider provides a mock function for the type MockAuth
func (_mock *MockAuth) ConfiguredProvider() []account.Type {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConfiguredProvider")
	}

	var r0 []account.Type
	if returnFunc, ok := ret.Get(0).(func() []account.Type); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]account.Type)
		}
	}
	return r0
}

// MockAuth_ConfiguredProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfiguredProvider'
type MockAuth_ConfiguredProvider_Call struct {
	*mock.Call
}

// ConfiguredProvider is a helper method to define mock.On call
func (_e *MockAuth_Expecter) ConfiguredProvider() *MockAuth_ConfiguredProvider_Call {
	return &MockAuth_ConfiguredProvider_Call{Call: _e.mock.On("ConfiguredProvider")}
}

func (_c *MockAuth_ConfiguredProvider_Call) Run(run func()) *MockAuth_ConfiguredProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuth_ConfiguredProvider_Call) Return(types []account.Type) *MockAuth_ConfiguredProvider_Call {
	_c.Call.Return(types)
	return _c
}

func (_c *MockAuth_ConfiguredProvider_Call) RunAndReturn(run func() []account.Type) *MockAuth_ConfiguredProvider_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockAuth
func (_mock *MockAuth) CreateUser(ctx context.Context, userInfo UserInformation) (*users.User, string, error) {
	ret := _mock.Called(ctx, userInfo)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *users.User
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, UserInformation) (*users.User, string, error)); ok {
		return returnFunc(ctx, userInfo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, UserInformation) *users.User); ok {
		r0 = returnFunc(ctx, userInfo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, UserInformation) string); ok {
		r1 = returnFunc(ctx, userInfo)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, UserInformation) error); ok {
		r2 = returnFunc(ctx, userInfo)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuth_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockAuth_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userInfo UserInformation
func (_e *MockAuth_Expecter) CreateUser(ctx any, userInfo any) *MockAuth_CreateUser_Call {
	return &MockAuth_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, userInfo)}
}

func (_c *MockAuth_CreateUser_Call) Run(run func(ctx context.Context, userInfo UserInformation)) *MockAuth_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 UserInformation
		if args[1] != nil {
			arg1 = args[1].(UserInformation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuth_CreateUser_Call) Return(user *users.User, s string, err error) *MockAuth_CreateUser_Call {
	_c.Call.Return(user, s, err)
	return _c
}

func (_c *MockAuth_CreateUser_Call) RunAndReturn(run func(ctx context.Context, userInfo UserInformation) (*users.User, string, error)) *MockAuth_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetProvider provides a mock function for the type MockAuth
func (_mock *MockAuth) GetProvider(accountType account.Type) (AuthProvider, error) {
	ret := _mock.Called(accountType)

	if len(ret) == 0 {
		panic("no return value specified for GetProvider")
	}

	var r0 AuthProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(account.Type) (AuthProvider, error)); ok {
		return returnFunc(accountType)
	}
	if returnFunc, ok := ret.Get(0).(func(account.Type) AuthProvider); ok {
		r0 = returnFunc(accountType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(AuthProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(account.Type) error); ok {
		r1 = returnFunc(accountType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuth_GetProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProvider'
type MockAuth_GetProvider_Call struct {
	*mock.Call
}

// GetProvider is a helper method to define mock.On call
//   - accountType account.Type
func (_e *MockAuth_Expecter) GetProvider(accountType any) *MockAuth_GetProvider_Call {
	return &MockAuth_GetProvider_Call{Call: _e.mock.On("GetProvider", accountType)}
}

func (_c *MockAuth_GetProvider_Call) Run(run func(accountType account.Type)) *MockAuth_GetProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 account.Type
		if args[0] != nil {
			arg0 = args[0].(account.Type)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuth_GetProvider_Call) Return(authProvider AuthProvider, err error) *MockAuth_GetProvider_Call {
	_c.Call.Return(authProvider, err)
	return _c
}

func (_c *MockAuth_GetProvider_Call) RunAndReturn(run func(accountType account.Type) (AuthProvider, error)) *MockAuth_GetProvider_Call {
	_c.Call.Return(run)
	return _c
}

// Sign provides a mock function for the type MockAuth
func (_mock *MockAuth) Sign(claims map[string]any) (string, error) {
	ret := _mock.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(map[string]any) (string, error)); ok {
		return returnFunc(claims)
	}
	if returnFunc, ok := ret.Get(0).(func(map[string]any) string); ok {
		r0 = returnFunc(claims)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(map[string]any) error); ok {
		r1 = returnFunc(claims)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuth_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockAuth_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - claims map[string]any
func (_e *MockAuth_Expecter) Sign(claims any) *MockAuth_Sign_Call {
	return &MockAuth_Sign_Call{Call: _e.mock.On("Sign", claims)}
}

func (_c *MockAuth_Sign_Call) Run(run func(claims map[string]any)) *MockAuth_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]any
		if args[0] != nil {
			arg0 = args[0].(map[string]any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuth_Sign_Call) Return(s string, err error) *MockAuth_Sign_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuth_Sign_Call) RunAndReturn(run func(claims map[string]any) (string, error)) *MockAuth_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// Verifier provides a mock function for the type MockAuth
func (_mock *MockAuth) Verifier() func(http.Handler) http.Handler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Verifier")
	}

	var r0 func(http.Handler) http.Handler
	if returnFunc, ok := ret.Get(0).(func() func(http.Handler) http.Handler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(http.Handler) http.Handler)
		}
	}
	return r0
}

// MockAuth_Verifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verifier'
type MockAuth_Verifier_Call struct {
	*mock.Call
}

// Verifier is a helper method to define mock.On call
func (_e *MockAuth_Expecter) Verifier() *MockAuth_Verifier_Call {
	return &MockAuth_Verifier_Call{Call: _e.mock.On("Verifier")}
}

func (_c *MockAuth_Verifier_Call) Run(run func()) *MockAuth_Verifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuth_Verifier_Call) Return(fn func(http.Handler) http.Handler) *MockAuth_Verifier_Call {
	_c.Call.Return(fn)
	return _c
}

func (_c *MockAuth_Verifier_Call) RunAndReturn(run func() func(http.Handler) http.Handler) *MockAuth_Verifier_Call {
	_c.Call.Return(run)
	return _c
}
