---
structname: "Mock{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
filename: "mock_{{.InterfaceName}}.go"
packages:
  # configuration on package level
  net/http:
    config:
      dir: mocks/net/http
    interfaces:
      ResponseWriter:

  scrumlr.io/server/timeprovider:
    interfaces:
      TimeProvider:

  scrumlr.io/server/auth:
    interfaces:
      AuthService:
      AuthApi:

  scrumlr.io/server/boards:
    interfaces:
      BoardService:
      BoardDatabase:

  scrumlr.io/server/realtime:
    interfaces:
      Client:

  scrumlr.io/server/reactions:
    interfaces:
      ReactionService:
      ReactionDatabase:

  scrumlr.io/server/hash:
    interfaces:
      Hash:

  scrumlr.io/server/health:
    interfaces:
      HealthService:
      HealthDatabase:

  scrumlr.io/server/sessions:
    interfaces:
      SessionService:
      SessionDatabase:
      SessionApi:

  scrumlr.io/server/sessionrequests:
    interfaces:
      SessionRequestService:
      SessionRequestDatabase:
      Websocket:

  scrumlr.io/server/users:
    interfaces:
      UserService:
      UserDatabase:
      UsersApi:

  scrumlr.io/server/notes:
    interfaces:
      NotesService:
      NotesDatabase:

  scrumlr.io/server/votings:
    interfaces:
      VotingService:
      VotingDatabase:

  scrumlr.io/server/columntemplates:
    interfaces:
      ColumnTemplateService:
      ColumnTemplateDatabase:

  scrumlr.io/server/boardtemplates:
    interfaces:
      BoardTemplateService:
      BoardTemplateDatabase:

  scrumlr.io/server/columns:
    interfaces:
      ColumnService:
      ColumnDatabase:
