with-expecter: true
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "mock_{{.InterfaceName}}.go"
resolve-type-alias: false
issue-845-fix: true
packages:
  # configuration on package level
  scrumlr.io/server/services:
    config:
      # generate for all interfaces in services a mock (for example: mock_Boards)
      all: true
