apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrumlr-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrumlr-frontend
  template:
    metadata:
      labels: 
        app: scrumlr-frontend
    spec:
      containers:
        - name: scrumlr-frontend
          image: scrumlr-frontend
          imagePullPolicy: IfNotPresent
          ports:
            - name: frontendport
              containerPort: 80
          livenessProbe: 
            httpGet:
              path: /
              port: frontendport
            initialDelaySeconds: 5
            periodSeconds: 3
          readinessProbe: 
            httpGet:
              path: /
              port: frontendport
            initialDelaySeconds: 3
            periodSeconds: 3
      restartPolicy: Always