apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrumlr-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrumlr-frontend
  template:
    metadata:
      labels: 
        app: scrumlr-frontend
    spec:
      containers:
        - name: scrumlr-frontend
          image: scrumlr-frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 80
      restartPolicy: Always