apiVersion: v1
kind: Service
metadata:
  name: scrumlr-frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080
  selector:
    app: scrumlr-frontend