// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package common

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBoardLastModifiedUpdater creates a new instance of MockBoardLastModifiedUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBoardLastModifiedUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBoardLastModifiedUpdater {
	mock := &MockBoardLastModifiedUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBoardLastModifiedUpdater is an autogenerated mock type for the BoardLastModifiedUpdater type
type MockBoardLastModifiedUpdater struct {
	mock.Mock
}

type MockBoardLastModifiedUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBoardLastModifiedUpdater) EXPECT() *MockBoardLastModifiedUpdater_Expecter {
	return &MockBoardLastModifiedUpdater_Expecter{mock: &_m.Mock}
}

// UpdateLastModified provides a mock function for the type MockBoardLastModifiedUpdater
func (_mock *MockBoardLastModifiedUpdater) UpdateLastModified(ctx context.Context, boardID uuid.UUID) error {
	ret := _mock.Called(ctx, boardID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastModified")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, boardID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBoardLastModifiedUpdater_UpdateLastModified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastModified'
type MockBoardLastModifiedUpdater_UpdateLastModified_Call struct {
	*mock.Call
}

// UpdateLastModified is a helper method to define mock.On call
//   - ctx context.Context
//   - boardID uuid.UUID
func (_e *MockBoardLastModifiedUpdater_Expecter) UpdateLastModified(ctx interface{}, boardID interface{}) *MockBoardLastModifiedUpdater_UpdateLastModified_Call {
	return &MockBoardLastModifiedUpdater_UpdateLastModified_Call{Call: _e.mock.On("UpdateLastModified", ctx, boardID)}
}

func (_c *MockBoardLastModifiedUpdater_UpdateLastModified_Call) Run(run func(ctx context.Context, boardID uuid.UUID)) *MockBoardLastModifiedUpdater_UpdateLastModified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBoardLastModifiedUpdater_UpdateLastModified_Call) Return(err error) *MockBoardLastModifiedUpdater_UpdateLastModified_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBoardLastModifiedUpdater_UpdateLastModified_Call) RunAndReturn(run func(ctx context.Context, boardID uuid.UUID) error) *MockBoardLastModifiedUpdater_UpdateLastModified_Call {
	_c.Call.Return(run)
	return _c
}
