cert:
  enabled: false
  name:
hostname: 

cache:
  name: cache
  replicas: 
  
dashboard:
  name: dashboard
  replicas: 
  image: scrumlr-dashboard
  imagePullPolicy: 
  config:
    SERVER_URL: "http://localhost/api"
    APP_ID: "Scrumlr"
    APP_NAME: "Scrumlr" 
    DASHBOARD_DEFAULT_USER: "scrumlr" 
  secrets:
    MASTER_KEY: bWFzdGVyS2V5
    DASHBOARD_DEFAULT_PASSWORD: JDJhJDEyJFFKcjZGUG1LU2hLNTFGekt3RkJnMnVabEpCV3IuOEpULkRwT1RCOXlIT3N1c2VPREY0amU2

frontend:
  name: frontend
  image: scrumlr-frontend
  imagePullPolicy: 
  replicas:


livequery:
  name: livequery
  replicas: 
  image: scrumlr-parse
  imagePullPolicy: 
  config:
    SCRUMLR_OPERATION_MODE: "livequery"
    SCRUMLR_DATABASE_URI: "mongodb://scrumlr-database:27017/dev"
    SCRUMLR_API_HOST: "scrumlr-server"
    SCRUMLR_API_PORT: "4000"
    SCRUMLR_SERVE_PRODUCTION_WEBAPP: "false"
    SCRUMLR_CACHE_URL: "redis://scrumlr-cache:6379"
  secrets:
    SCRUMLR_API_MASTER_KEY: bWFzdGVyS2V5

server:
  name: server
  image: scrumlr-parse
  imagePullPolicy: 
  replicas: 
  config:
    SCRUMLR_OPERATION_MODE: "server"
    SCRUMLR_DATABASE_URI: "mongodb://scrumlr-database:27017/dev"
    SCRUMLR_API_HOST: "localhost"
    SCRUMLR_API_PORT: "4000"
    SCRUMLR_SERVE_PRODUCTION_WEBAPP: "false"
    SCRUMLR_CACHE_URL: "redis://scrumlr-cache:6379"
  secrets:
    SCRUMLR_API_MASTER_KEY: bWFzdGVyS2V5

mongodb:
  fullnameOverride: scrumlr-database
  image:
    pullPolicy: IfNotPresent
  persistence:
    enabled: false
  auth:
    enabled: false
  labels: { 
    app.kubernetes.io/name: scrumlr-database,
    app.kubernetes.io/components: database,
    app.kubernetes.io/part-of: scrumlr
  }


