apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-configmap
  namespace: {{ .Release.Namespace }}
data:
  SCRUMLR_LISTEN_PORT: {{ .Values.frontend.config.listenPort | quote }}
  SCRUMLR_SERVER_URL: {{ .Values.frontend.config.serverUrl | quote }}
  {{- range $key, $val := .Values.frontend.extraConfig }}
  {{ $key | upper }}: {{ $val | quote }}
  {{- end }}
