{{- if .Values.frontend.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-frontend-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.frontend.secrets }}
  {{ $key | upper }}: {{ $val | b64enc }}
  {{- end }}
{{- end }}
