#!/bin/sh
SCRIPT_DIRECTORY=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PATH="$PATH:$SCRIPT_DIRECTORY/../node_modules/.bin"
. "$SCRIPT_DIRECTORY/_/husky.sh"

echo "... about to format staged files for client"
lint-staged

echo "... about to format staged files for server"
cd server/
lint-staged
