# Checks if deployed dev-cluster is reachable from public users

name: Check PR dev cluster reachability
on:
  workflow_call:
    inputs:
      base_url:
        required: true
        description: "Base URL to test against"
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check reachability of deployed dev cluster
        id: wait-for-cluster
        env:
          BASE_URL: ${{ inputs.base_url }}
        run: |
          retry=1
          reachable=false
          max_retries=3
          until [ $retry -gt $max_retries ]
          do
            response=$(curl -s -k -o /dev/null -w "%{http_code}" "$BASE_URL/api/health")
            if [ $response = "204" ]; then
              echo "Cluster is healthy! Continuing..."
              reachable=true
              break
            else
              echo "Cluster is not responding. Retrying in $((5 * retry)) seconds..."
              sleep $((5 * retry))
            fi
            retry=$((retry + 1))
          done
          if [ $reachable == false ]; then
            echo "max_retries=$max_retries" >> $GITHUB_OUTPUT
            echo "response_code=$response" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Set annotation when cluster not reachable
        if: steps.wait-for-cluster.outcome != 'success'
        run: |
           echo "::error title=DevClusterNotReachable::Cluster is not responding after ${{ steps.wait-for-cluster.outputs.max_retries }} attempts. Last HTTP-Code: ${{ steps.wait-for-cluster.outputs.response_code }}"