---
name: Deduplicate dependabot PRs
on:
  push:
    branches:
      - "dependabot/npm_and_yarn/*"
    paths:
      - "**/package.json"
      - "yarn.lock"

jobs:
  dedupe:
    name: Deduplicate yarn dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Corepack # for yarn berry
        run: |
          npm install -g corepack@0.36.0 --ignore-scripts
          corepack enable
          corepack install

      - name: Setup Node.js with cache
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "26"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Deduplicate dependencies
        run: yarn dedupe

      - name: Setup git
        run: |
          git config user.name "Scrumlr Dedup Bot[bot]"
          git config user.email \<\>

      - name: Commit and push changes
        run: |
          git add yarn.lock
          git commit -m "Deduplicate yarn dependencies [dependabot skip]" || echo "No changes to commit"
          git push origin ${{ github.ref_name }}

