# deploy to dev cluster using own runner

name: Deploy to dev cluster
on:
  workflow_call:
    inputs:
      frontend_image_tag:
        required: true
        description: "frontend image tag"
        type: string
      server_image_tag:
        required: true
        description: "server image tag"
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
      actions: read
      pull-requests: write
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@829323503d1be3d00ca8346e5391ca0b07a9ab0d # v5.1.0
        id: install

      - name: Set up Kubernetes Auth
        uses: azure/k8s-set-context@89b837d75b40a7bd2ddafde837473c212db8b313 # v5.0.0
        with:
          method: service-account
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
          k8s-url: https://kubernetes.default.svc

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Replace template variables
        run: |
          if [ -z "${{ github.event.pull_request.number }}" ]; then
            echo "No pull request number found. This was triggered by the main branch. Using main instead of PR_NUMBER"
            sed -i "s#PR_NUMBER#main#g" k8s/deployment.yaml
          else
            sed -i "s#PR_NUMBER#${{ github.event.pull_request.number }}#g" k8s/deployment.yaml
          fi
          sed -i "s#POSTGRES_DEV_PASSWORD#${{ secrets.POSTGRES_DEV_PASSWORD }}#g" k8s/deployment.yaml

      - name: json_debug
        run: |
          cat k8s/deployment.yaml

      - name: Deploy to dev cluster
        uses: Azure/k8s-deploy@c7ebd0d5f39477a23f1b5dea0f52e6db04adf28e # v6.0.0
        with:
          namespace: scrumlr-dev-deployments
          force: true
          pull-images: false
          manifests: |
            k8s/deployment.yaml
          images: |
            ghcr.io/inovex/scrumlr.io/scrumlr-frontend:${{ inputs.frontend_image_tag }}
            ghcr.io/inovex/scrumlr.io/scrumlr-server:${{ inputs.server_image_tag }}

      - name: send_github_message
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          message: |
            The deployment to the dev cluster was successful. You can find the deployment here: https://${{ github.event.pull_request.number }}.development.scrumlr.fra.ics.inovex.io
            This deployment is only for testing purposes and will be deleted after 1 week.
            To redeploy rerun the workflow.
            <strong>DO NOT STORE IMPORTANT DATA ON THIS DEPLOYMENT</strong>

            <details>
            <summary>Deployed Images</summary>

            - ghcr.io/inovex/scrumlr.io/scrumlr-frontend:${{ inputs.frontend_image_tag }}

            - ghcr.io/inovex/scrumlr.io/scrumlr-server:${{ inputs.server_image_tag }}

            </details>
          comment_tag: dev-deployment
          mode: recreate
