name: dev-CI
on:
  pull_request:
    branches: [ master ]
jobs:
  install:
    name: Installing dependencies
    strategy:
      matrix:
        node: [ 13 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Upload workspace
        uses: actions/upload-artifact@v1
        with:
          name: dependencies
          path: .
  prettier-check:
    name: Checking the formatting
    needs: [ install ]
    strategy:
      matrix:
        node: [ 13 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v1
        with:
          name: dependencies
      - name: Checking prettied files
        run: npm run prettier:check
  eslint-check:
    name: Checking with eslint
    needs: [ install ]
    strategy:
      matrix:
        node: [ 13 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v1
        with:
          name: dependencies
        # TODO #118: - name: Checking files with eslint
        # TODO #118: run: npm run lint
  test-check:
    name: Checking with test & coverage
    needs: [ install ]
    strategy:
      matrix:
        node: [ 13 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v1
        with:
          name: dependencies
      - name: Checking with eslint
        run: npm test -- --coverage --watchAll=false
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/clover.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
