name: Create and publish Docker images

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Log in to Github Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
       
      - name: Build and push Frontend
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: inovex/scrumlr.io/scrumlr-frontend:latest
      
      - name: Build and push Dashboard
        uses: docker/build-push-action@v2
        with:
          context: ./dashboard
          push: true
          tags: inovex/scrumlr.io/scrumlr-dashboard:latest

      - name: Build and push Server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: inovex/scrumlr.io/scrumlr-server:latest
          
