apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "scrumlr-fullname" .Values.frontend }}
  labels: 
    {{- include "selectorLabels" .Values.frontend | nindent 6}}
    {{- include "labels" . | nindent 6}}
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.frontend.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "scrumlr-fullname" .Values.frontend }}
            port:
              number: {{ .Values.frontend.port }}