apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "scrumlr-fullname" .Values.frontend }}
  labels: 
    {{- include "selectorLabels" .Values.frontend | nindent 6}}
    {{- include "labels" . | nindent 6}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.frontend.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "scrumlr-fullname" .Values.frontend }}
            port:
              number: {{ .Values.frontend.port }} 
      - path: /new
        pathType: Prefix
        backend:
          service:
            name: {{ include "scrumlr-fullname" .Values.frontend }}
            port:
              number: {{ .Values.frontend.port }} 
      - path: /login 
        pathType: Prefix
        backend:
          service:
            name: {{ include "scrumlr-fullname" .Values.frontend }}
            port:
              number: {{ .Values.frontend.port }} 
      - path: /board/
        pathType: Prefix
        backend:
          service:
            name: {{ include "scrumlr-fullname" .Values.frontend }}
            port:
              number: {{ .Values.frontend.port }}      
